const fs=require('fs'),assert=require('assert');
const peopleGrid=fs.readFileSync('src/app-2.js','utf8');
const recordModal=fs.readFileSync('src/app-record-modal.js','utf8');
const userLink=fs.readFileSync('src/app-person-user-link.js','utf8');
const roleModel=fs.readFileSync('src/app-role-model.js','utf8');
const actuals=fs.readFileSync('src/app-actuals.js','utf8');
const resourcePlan=fs.readFileSync('src/app-4.js','utf8');
const reportingModel=fs.readFileSync('src/app-reporting-model.js','utf8');
const appCore=fs.readFileSync('src/app-1.js','utf8');
const remoteWorkspace=fs.readFileSync('src/app-remote-workspace.js','utf8');
const index=fs.readFileSync('src/index.html','utf8');
const acceptanceSteps=fs.readFileSync('tests/e2e/steps/release.steps.cjs','utf8');
assert.match(peopleGrid,/key:'staffNumber',label:'Staff Number \*'/);
assert.match(recordModal,/modalField\('Staff Number','staffNumber'/);
assert.match(userLink,/modalField\('Linked User','userId'/);
assert.match(userLink,/modalField\('Staff Number','staffNumber'/);
assert.match(roleModel,/const baseRenderTeamRole=renderTeamModal/);
assert.match(roleModel,/existing\.includes\('data-modal-field="roleId"'\)/);
assert.match(roleModel,/modalField\('Staff Number','staffNumber'/);
assert.match(actuals,/'Staff Number':\['People #','Person #'\]/);
assert.match(actuals,/person\?\.staffNumber/);
assert.doesNotMatch(actuals,/person\?\.personNumber/);
assert.match(actuals,/unmatchedStaffRows/);
assert.match(actuals,/outOfScopePersonlessRows/);
assert.match(actuals,/unmatchedProjectRows/);
assert.match(resourcePlan,/Loading Actuals…/);
assert.match(resourcePlan,/addEventListener\('amo:reporting-model-updated'.*renderResource\(\)/s);
assert.match(resourcePlan,/Actuals reporting unavailable:/);
assert.match(resourcePlan,/reportingReady\?\(actual\(m\)\?'ACTUAL':'FORECAST'\):'LOADING'/);
assert.ok(index.includes('app-reporting-model.js?v=20260903-2'),'ReportingModel is not loaded by the application shell.');
assert.ok(index.indexOf('app-reporting-model.js?v=20260903-2')<index.indexOf('app-4.js?v=20260903-2'),'ReportingModel must load before Resource Plan.');
assert.match(reportingModel,/detail:\{error:String\(error\?\.message\|\|error\)\}/);
assert.match(appCore,/function notifyWorkspaceConnected\(/);
assert.match(appCore,/CustomEvent\('amo-workspace-connected'/);
assert.match(appCore,/resetEdits\(\);notifyWorkspaceConnected\('local'\);refreshAll\(\)/);
assert.match(remoteWorkspace,/notifyWorkspaceConnected\('remote'\);\s*refreshAll\(\)/);
assert.doesNotMatch(acceptanceSteps,/waitForLoadState\('networkidle'/);
assert.match(acceptanceSteps,/window\.AMO_CONFIG\?\.targetStage/);
console.log('Staff Number, Actuals reporting and workspace lifecycle contract tests passed');
