const fs=require('fs'),assert=require('assert');
const peopleGrid=fs.readFileSync('src/app-2.js','utf8');
const recordModal=fs.readFileSync('src/app-record-modal.js','utf8');
const userLink=fs.readFileSync('src/app-person-user-link.js','utf8');
const roleModel=fs.readFileSync('src/app-role-model.js','utf8');
const actuals=fs.readFileSync('src/app-actuals.js','utf8');
const resourcePlan=fs.readFileSync('src/app-4.js','utf8');
assert.match(peopleGrid,/key:'staffNumber',label:'Staff Number \*'/);
assert.match(recordModal,/modalField\('Staff Number','staffNumber'/);
assert.match(userLink,/modalField\('Linked User','userId'/);
assert.match(userLink,/modalField\('Staff Number','staffNumber'/);
assert.match(roleModel,/const baseRenderTeamRole=renderTeamModal/);
assert.match(roleModel,/existing\.includes\('data-modal-field="roleId"'\)/);
assert.match(roleModel,/modalField\('Staff Number','staffNumber'/);
assert.match(actuals,/person\?\.staffNumber/);
assert.doesNotMatch(actuals,/person\?\.personNumber/);
assert.match(resourcePlan,/Loading Actuals…/);
assert.match(resourcePlan,/addEventListener\('amo:reporting-model-updated'.*renderResource\(\)/s);
assert.match(resourcePlan,/reportingReady\?\(actual\(m\)\?'ACTUAL':'FORECAST'\):'LOADING'/);
console.log('Staff Number and Actuals reporting contract tests passed');
