const assert=require('node:assert/strict');const {spawn}=require('node:child_process');const {chromium}=require('playwright');
(async()=>{const server=spawn(process.execPath,['tests/e2e/bin/serve-target-client.cjs'],{stdio:['ignore','pipe','inherit']});try{
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Local target-client server did not start.')),5000);server.stdout.on('data',chunk=>{if(String(chunk).includes('listening')){clearTimeout(timer);resolve()}});server.on('exit',code=>reject(new Error(`Server exited ${code}`))) });
  const browser=await chromium.launch({headless:true});const context=await browser.newContext();const page=await context.newPage();await page.goto('http://127.0.0.1:4173/demand?e2e=1');await page.waitForSelector('.demand-row');
  const ids=()=>page.locator('.demand-row').evaluateAll(rows=>rows.map(r=>r.dataset.demandId));
  assert.deepEqual(await ids(),['DEM-2026-0001','DEM-2026-0002']);
  await page.selectOption('[data-filter="projectNumber"]','present');assert.deepEqual(await ids(),['DEM-2026-0001']);assert.match(await page.locator('#demandCount').textContent(),/Showing 1/);
  await page.selectOption('[data-filter="control"]','funding-missing');assert.deepEqual(await ids(),[],'Combined filters must be a true intersection.');
  await page.click('[data-clear]');await page.selectOption('[data-filter="control"]','actuals-missing');assert.deepEqual(await ids(),['DEM-2026-0002'],'Actuals missing must derive from the latest available period and due allocations.');assert.match(await page.locator('.demand-row[data-demand-id="DEM-2026-0002"]').innerHTML(),/Actuals missing/);
  await page.click('[data-clear]');await page.selectOption('[data-filter="show"]','all');assert.deepEqual(await ids(),['DEM-2026-0001','DEM-2026-0002','DEM-2026-0003']);

  await page.selectOption('[data-scope-mode]','team');await page.selectOption('[data-team]','TEAM-B');assert.deepEqual(await ids(),['DEM-2026-0003'],'Team scope must honour canonical teamId records.');
  await page.selectOption('[data-scope-mode]','department');await page.selectOption('[data-department]','DEP-B');assert.deepEqual(await ids(),['DEM-2026-0003'],'Department scope must resolve configured team membership.');
  await page.selectOption('[data-scope-mode]','all');await page.selectOption('[data-filter="show"]','active');

  const demandRow=page.locator('.demand-row[data-demand-id="DEM-2026-0001"]'),toggle=demandRow.locator('.tree-toggle');await toggle.click();assert.equal(await toggle.getAttribute('aria-expanded'),'true','Expanded Demand must expose hierarchy state to assistive technology.');const wpRow=page.locator('.work-package-row[data-work-package-id="WP-1"]');assert.equal(await wpRow.count(),1);assert.equal(await wpRow.locator('[data-edit-work-package]').count(),1,'Work Package rows need an explicit View / edit backstop.');const workItemLink=wpRow.locator('a');assert.equal(await workItemLink.textContent(),'#9001');assert.equal(await workItemLink.getAttribute('href'),'https://dev.azure.com/amo-test/Architecture/_workitems/edit/9001');

  const dialog=page.locator('dialog');await demandRow.locator('td').nth(2).dblclick();assert.equal(await dialog.getAttribute('aria-labelledby'),'demand-editor-title','Demand row double-click must open the Demand editor.');await page.click('dialog button[value="cancel"]');await dialog.waitFor({state:'hidden'});
  await wpRow.locator('td').nth(3).dblclick();assert.equal(await dialog.getAttribute('aria-labelledby'),'work-package-editor-title','Work Package row double-click must open the Work Package editor.');await page.fill('dialog input[name="title"]','Modal edited package');await page.click('dialog [data-save]');await dialog.waitFor({state:'hidden'});assert.match(await page.locator('.work-package-row[data-work-package-id="WP-1"]').textContent(),/Modal edited package/);

  await page.click('[data-action="editList"]');assert.equal(await page.locator('.demand-row[data-demand-id="DEM-2026-0001"] [data-inline-entity="demand"]').count(),6,'Edit List must edit the fields already displayed on the Demand row.');assert.ok(await page.locator('.work-package-row[data-work-package-id="WP-1"] [data-inline-entity="workPackage"]').count()>=5,'Expanded Work Package must remain nested and become editable.');
  await page.fill('.demand-row[data-demand-id="DEM-2026-0001"] [data-field="projectNumber"]','54321');await page.locator('.demand-row[data-demand-id="DEM-2026-0001"] [data-field="projectNumber"]').press('Tab');await page.selectOption('.demand-row[data-demand-id="DEM-2026-0001"] [data-field="status"]','Planned');
  await page.fill('.work-package-row[data-work-package-id="WP-1"] [data-field="title"]','Inline edited package');await page.locator('.work-package-row[data-work-package-id="WP-1"] [data-field="title"]').press('Tab');await page.selectOption('.work-package-row[data-work-package-id="WP-1"] [data-field="status"]','Ready');await page.fill('.work-package-row[data-work-package-id="WP-1"] [data-field="azureDevOpsWorkItemId"]','9010');await page.locator('.work-package-row[data-work-package-id="WP-1"] [data-field="azureDevOpsWorkItemId"]').press('Tab');
  await page.click('[data-action="saveList"]');await page.waitForFunction(()=>document.querySelector('[data-action="editList"]')?.hidden===false);await page.reload();await page.waitForSelector('.demand-row');assert.match(await page.locator('.demand-row[data-demand-id="DEM-2026-0001"]').textContent(),/54321/,'Demand list edits must survive browser reload.');await page.locator('.demand-row[data-demand-id="DEM-2026-0001"] .tree-toggle').click();assert.match(await page.locator('.work-package-row[data-work-package-id="WP-1"]').textContent(),/Inline edited package/,'Work Package list edits must survive browser reload.');assert.match(await page.locator('.work-package-row[data-work-package-id="WP-1"]').textContent(),/Ready/);assert.equal(await page.locator('.work-package-row[data-work-package-id="WP-1"] a').textContent(),'#9010');

  await page.click('.demand-row[data-demand-id="DEM-2026-0001"] [data-edit]');assert.equal(await dialog.getAttribute('aria-labelledby'),'demand-editor-title');assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('name')),'title','Demand editor must place keyboard focus in the title field.');await page.fill('dialog input[name="title"]','Persisted edited title');await page.click('dialog [data-save]');await dialog.waitFor({state:'hidden'});await page.reload();await page.waitForSelector('.demand-row');assert.match(await page.locator('.demand-row[data-demand-id="DEM-2026-0001"] .row-title').textContent(),/Persisted edited title/,'Edit must survive browser reload.');
  await page.click('[data-action="new"]');await page.fill('dialog input[name="title"]','Created by deterministic E2E');await page.selectOption('dialog select[name="businessArea"]','Customer');await page.selectOption('dialog select[name="teamId"]','TEAM-B');await page.click('dialog [data-save]');await page.locator('dialog').waitFor({state:'hidden'});assert.equal(await page.locator('.demand-row[data-demand-id="DEM-2026-0004"]').count(),1);await page.reload();await page.waitForSelector('.demand-row[data-demand-id="DEM-2026-0004"]');assert.match(await page.locator('.demand-row[data-demand-id="DEM-2026-0004"] .row-title').textContent(),/Created by deterministic E2E/,'Created Demand must survive reload.');await page.selectOption('[data-scope-mode]','team');await page.selectOption('[data-team]','TEAM-B');assert.deepEqual(await ids(),['DEM-2026-0004'],'Created Demand team ownership must survive reload and drive scope.');

  await page.selectOption('[data-scope-mode]','all');await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForSelector('.demand-row');assert.equal(await page.locator('.target-client-app').count(),1,'Demand must remain available at mobile viewport.');assert.equal(await page.locator('.demand-row [data-edit]').first().count(),1,'View / edit remains available as the mobile edit backstop.');
  await browser.close();console.log('Target client Demand browser E2E passed.');
}finally{server.kill('SIGTERM')}})().catch(error=>{console.error(error);process.exit(1)});
