const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const assert=require('node:assert/strict');
function moduleDataUrl(file){const absolute=path.resolve(file);let source=fs.readFileSync(absolute,'utf8');source=source.replace(/from\s+(['"])(\.\.?\/[^'"]+)\1/g,(_m,_q,s)=>`from '${moduleDataUrl(path.resolve(path.dirname(absolute),s))}'`);return`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`}
async function importSource(file){return import(moduleDataUrl(file))}
function notFound(){const e=new Error('Not found');e.name='NotFoundError';return e}
class MemoryFileHandle{constructor(name,node){this.name=name;this.kind='file';this.node=node}async getFile(){return{text:async()=>this.node.text,arrayBuffer:async()=>Buffer.from(this.node.text)}}async createWritable(){return{write:async value=>{this.node.text=typeof value==='string'?value:Buffer.from(value).toString()},close:async()=>{}}}}
class MemoryDirectoryHandle{constructor(name='Workspace'){this.name=name;this.kind='directory';this.children=new Map()}async queryPermission(){return'granted'}async requestPermission(){return'granted'}async getDirectoryHandle(name,{create=false}={}){let node=this.children.get(name);if(!node&&create){node=new MemoryDirectoryHandle(name);this.children.set(name,node)}if(!node||node.kind!=='directory')throw notFound();return node}async getFileHandle(name,{create=false}={}){let node=this.children.get(name);if(!node&&create){node={kind:'file',text:''};this.children.set(name,node)}if(!node||node.kind!=='file')throw notFound();return new MemoryFileHandle(name,node)}async removeEntry(name){if(!this.children.delete(name))throw notFound()}async *entries(){for(const [name,node] of this.children)yield[name,node.kind==='directory'?node:new MemoryFileHandle(name,node)]}}
async function seed(root,filePath,value){const parts=filePath.split('/'),name=parts.pop();let dir=root;for(const part of parts)dir=await dir.getDirectoryHandle(part,{create:true});const handle=await dir.getFileHandle(name,{create:true}),w=await handle.createWritable();await w.write(JSON.stringify(value));await w.close()}
function browserContext(fetchImpl=async()=>{throw new Error('Unexpected fetch')}){const window={amoAuth:{getApiToken:async()=>null,isSignedIn:()=>true,currentIdentity:()=>({name:'Test'})},dispatchEvent(){}};const context={window,fetch:fetchImpl,console,CustomEvent:function(){},document:{querySelector:()=>({})},URL,encodeURIComponent,decodeURIComponent,setTimeout,clearTimeout};window.window=window;return vm.createContext(context)}
function runLegacy(context,file){vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file})}
function response(data,status=200){return{ok:status>=200&&status<300,status,text:async()=>data==null?'':JSON.stringify(data)}}

(async()=>{
  const {capabilityApiForRepository}=await importSource('src/client/data/capability-api.js');

  // Local path: canonical API -> real LocalWorkspaceRepository -> File System Access-shaped handles.
  const localContext=browserContext();runLegacy(localContext,'src/app-workspace-repository.js');const root=new MemoryDirectoryHandle('Local Acceptance Workspace');
  await seed(root,'workspace.json',{type:'architecture-operations-hub',name:'Local Acceptance Workspace'});await seed(root,'config/settings.json',{services:['Architecture']});await seed(root,'demand/DEM-1.json',{id:'DEM-1',title:'Local demand'});await seed(root,'team/P-1.json',{id:'P-1',name:'Local person'});await seed(root,'allocations/A-1.json',{id:'A-1',demandId:'DEM-1'});await seed(root,'work-packages/WP-1.json',{id:'WP-1',demandId:'DEM-1'});await seed(root,'actuals/2026-09.json',{month:'2026-09',facts:[{id:'LOCAL'}]});
  const local=capabilityApiForRepository(new localContext.window.LocalWorkspaceRepository(root));assert.equal(local.mode,'local');assert.equal((await local.demand.list())[0].title,'Local demand');assert.equal((await local.people.list())[0].name,'Local person');assert.equal((await local.workPackages.list())[0].id,'WP-1');assert.equal((await local.allocations.list())[0].id,'A-1');assert.equal((await local.actuals.latestPeriod()).facts[0].id,'LOCAL');await local.demand.save({id:'DEM-2',title:'Saved locally'});assert.equal((await local.demand.get('DEM-2')).title,'Saved locally');await local.settings.save({services:['Data']});assert.deepEqual(JSON.parse(JSON.stringify(await local.settings.get())),{services:['Data']});

  // Remote path: canonical API -> real RemoteWorkspaceRepository -> HTTP API routes.
  const requests=[],remoteRecords={demand:[{id:'DEM-1',title:'Remote demand'}],team:[{id:'P-1',name:'Remote person'}],allocations:[{id:'A-1'}],workPackages:[{id:'WP-1'}]};let remoteSettings={services:['Architecture']};
  const remoteFetch=async(url,options={})=>{const u=new URL(url),p=u.pathname;requests.push([options.method||'GET',p]);if(p==='/api/info')return response({product:'AMO',apiVersion:'2',workspaceName:'Remote Acceptance Workspace'});const recordMatch=p.match(/^\/api\/records\/([^/]+)(?:\/([^/]+))?$/);if(recordMatch){const type=decodeURIComponent(recordMatch[1]),id=recordMatch[2]&&decodeURIComponent(recordMatch[2]);if(!id)return response(remoteRecords[type]||[]);if(options.method==='PUT'){const next=JSON.parse(options.body);const rows=remoteRecords[type]||(remoteRecords[type]=[]),i=rows.findIndex(x=>x.id===id);i>=0?rows.splice(i,1,next):rows.push(next);return response({record:next})}return response((remoteRecords[type]||[]).find(x=>x.id===id)||null)}if(p==='/api/settings'){if(options.method==='PUT'){remoteSettings=JSON.parse(options.body);return response({record:remoteSettings})}return response(remoteSettings)}if(p==='/api/actuals')return response({periods:['2026-09'],manifest:{latestPeriod:'2026-09'}});if(p==='/api/actuals/2026-09')return response({month:'2026-09',facts:[{id:'REMOTE'}]});throw new Error(`Unexpected remote API path ${p}`)};
  const remoteContext=browserContext(remoteFetch);remoteContext.WorkspaceRepository=undefined;runLegacy(remoteContext,'src/app-workspace-repository.js');remoteContext.WorkspaceRepository=remoteContext.window.WorkspaceRepository;runLegacy(remoteContext,'src/app-workspace-remote-repository.js');const remoteRepository=new remoteContext.window.RemoteWorkspaceRepository('https://amo.test');await remoteRepository.connect();const remote=capabilityApiForRepository(remoteRepository);assert.equal(remote.mode,'remote');assert.equal((await remote.demand.list())[0].title,'Remote demand');assert.equal((await remote.people.list())[0].name,'Remote person');assert.equal((await remote.workPackages.list())[0].id,'WP-1');assert.equal((await remote.allocations.list())[0].id,'A-1');assert.equal((await remote.actuals.latestPeriod()).facts[0].id,'REMOTE');await remote.demand.save({id:'DEM-2',title:'Saved remotely'});assert.equal((await remote.demand.get('DEM-2')).title,'Saved remotely');await remote.settings.save({services:['Data']});assert.deepEqual(JSON.parse(JSON.stringify(await remote.settings.get())),{services:['Data']});assert.ok(requests.some(([m,p])=>m==='GET'&&p==='/api/records/demand'));assert.ok(requests.some(([m,p])=>m==='GET'&&p==='/api/records/team'));assert.ok(requests.some(([m,p])=>m==='PUT'&&p==='/api/records/demand/DEM-2'));assert.ok(requests.some(([m,p])=>m==='GET'&&p==='/api/actuals/2026-09'));

  console.log('Target client capability API Local filesystem and Remote HTTP path tests passed.');
})().catch(error=>{console.error(error);process.exit(1)});
