function renderResource(){
  const rm=window.ReportingModel,months=planningPeriods(),activeTeam=db.team.filter(t=>t.active!==false),capacity=teamCapacity(),unmet=unresolvedWithoutAllocation();
  rm?.ensureLoaded?.();const reported=m=>rm?.reportedTotalFte?rm.reportedTotalFte(m):allocatedTotal(m),basis=m=>rm?.periodBasis?.(m)||'forecast',actual=m=>basis(m)==='actual';
  const peak=months.map(m=>({m,used:reported(m)})).sort((a,b)=>b.used-a.used)[0]||{m:months[0],used:0},overMonths=months.filter(m=>reported(m)>capacity).length;
  const now=new Date(),calendarCurrent=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`,currentMonth=months.includes(calendarCurrent)?calendarCurrent:(months[0]||calendarCurrent),currentUsed=reported(currentMonth),currentBasis=actual(currentMonth)?'actual effort':'forecast allocation';
  const coverage=rm?.coverageLabel?.()||'No Actuals loaded';
  $('resourceKpis').innerHTML=[['Available capacity',`${capacity.toFixed(1)} FTE`,'Active team baseline'],['Current reported effort',`${currentUsed.toFixed(1)} FTE`,`${monthLabel(currentMonth)} ${currentBasis}`],['Unmet demand',unmet.length,'Unresolved items with no resource'],['Over-capacity periods',overMonths,peak.m?`Peak ${monthLabel(peak.m)}: ${peak.used.toFixed(1)} FTE`:'No planning periods']].map(k=>`<div class="card"><div class="kpi-label">${k[0]}</div><div class="kpi-value">${k[1]}</div><div class="kpi-sub">${k[2]}</div></div>`).join('');
  const notice=$('resource')?.querySelector('.notice');if(notice)notice.innerHTML=`Reporting periods follow the <strong>Planning Window</strong>. <strong>${coverage}</strong>. Months with imported Actuals use observed effort; other months use allocation forecast. Allocations remain unchanged as the planning baseline.`;
  const monthHead=m=>`${monthLabel(m)}<br><span class="muted" style="font-size:.66rem">${actual(m)?'ACTUAL':'FORECAST'}</span>`,metric=(label,cls,fn)=>`<tr class="metric-row ${cls}"><td>${label}</td>${months.map(m=>`<td>${fn(m)}</td>`).join('')}</tr>`;
  $('resourceSummaryTable').innerHTML=`<thead><tr><th>Metric</th>${months.map(m=>`<th>${monthHead(m)}</th>`).join('')}</tr></thead><tbody>`+metric('Available capacity','metric-capacity',()=>`${capacity.toFixed(1)} FTE`)+metric('Reported effort','metric-allocated',m=>`${reported(m).toFixed(1)} FTE`)+metric('Remaining / over capacity',months.some(m=>reported(m)>capacity)?'metric-gap over':'metric-gap',m=>{const gap=capacity-reported(m);return `<span class="${gap<0?'over':''}">${gap>=0?'+':''}${gap.toFixed(1)} FTE</span>`})+metric('Utilisation','',m=>{const pct=capacity?Math.round(reported(m)/capacity*100):0;return `<span class="pill ${pct===0?'gray':pct>100?'red':pct>=85?'amber':'green'}">${pct}%</span>`})+`</tbody>`;
  $('unmetDemandPanel').innerHTML=!workspaceHandle?'<span class="muted">Open a workspace folder to load data.</span>':unmet.length?`<ul class="unmet-list">${unmet.map(d=>`<li><strong>${d.id}</strong> — ${d.title}<br><span class="muted">${d.priority||'—'} · ${d.service||'—'} · ${d.status||'—'}</span></li>`).join('')}</ul>`:'<span class="pill green">No unresolved demand without resource allocation</span>';
  const personUsed=(id,m)=>rm?.reportedFte?rm.reportedFte(id,null,m):allocationFor(id,m),overPeople=activeTeam.filter(t=>months.some(m=>personUsed(t.id,m)>(Number(t.fte)||0))),underNow=activeTeam.filter(t=>personUsed(t.id,currentMonth)<(Number(t.fte)||0)*.5),unplanned=rm?.unplannedFacts?.().length||0;
  $('resourceSignals').innerHTML=[['Team members',activeTeam.length],['People over capacity',overPeople.length],['People under 50% in current period',underNow.length],['Unmapped Actual facts',unplanned]].map(([l,v])=>`<div class="mini-stat"><span>${l}</span><strong>${v}</strong></div>`).join('');
  $('resourceUtilTable').innerHTML=`<thead><tr><th>Team member</th><th>Available FTE</th>${months.map(m=>`<th>${monthHead(m)}</th>`).join('')}</tr></thead><tbody>${activeTeam.map(t=>`<tr><td><strong>${t.name}</strong><br><span class="muted">${t.role||''}</span></td><td>${(Number(t.fte)||0).toFixed(1)}</td>${months.map(m=>{const used=personUsed(t.id,m),cap=Number(t.fte)||0,pct=cap?Math.round(used/cap*100):0,forecast=rm?.forecastFte?.(t.id,null,m)??allocationFor(t.id,m),variance=actual(m)?used-forecast:null;return `<td><span class="pill ${pct===0?'gray':pct>100?'red':pct>=85?'amber':'green'}">${pct}%</span><br><span class="muted">${used.toFixed(1)} FTE${variance==null?'':` · Δ ${variance>=0?'+':''}${variance.toFixed(1)}`}</span></td>`}).join('')}</tr>`).join('')}</tbody>`;
  const allocRows=[...db.allocations].sort((a,b)=>`${a.demandId}|${person(a.teamMemberId)?.name||a.teamMemberId}`.localeCompare(`${b.demandId}|${person(b.teamMemberId)?.name||b.teamMemberId}`));
  $('resourceAllocationDetail').innerHTML=`<thead><tr><th>Demand</th><th>Person</th>${months.map(m=>`<th>${monthHead(m)}</th>`).join('')}</tr></thead><tbody>${allocRows.map(a=>{const d=demandById(a.demandId);return `<tr><td><strong>${a.demandId}</strong><br><span class="muted">${d?.title||'Unknown demand'}</span></td><td>${person(a.teamMemberId)?.name||a.teamMemberId}</td>${months.map(m=>{const forecast=Number(a.forecast?.[m])||0;if(!actual(m))return`<td><strong>${Math.round(forecast*100)}%</strong><br><span class="muted">Forecast</span></td>`;const observed=rm?.actualFte?.(a.teamMemberId,a.demandId,m)||0,variance=observed-forecast;return`<td><strong>${Math.round(observed*100)}%</strong><br><span class="muted">Actual · plan ${Math.round(forecast*100)}% · Δ ${variance>=0?'+':''}${Math.round(variance*100)}%</span></td>`}).join('')}</tr>`}).join('')}</tbody>`;
}
