const CURRENT_YEAR=new Date().getFullYear();
const CURRENT_SCHEMA_VERSION=2;
const DEFAULT_SETTINGS={schemaVersion:CURRENT_SCHEMA_VERSION,planningWindow:{fromMonth:'',toMonth:''},financialPlanning:{roleDayRates:{}},statuses:[],services:[],businessAreas:[],initiatives:[],priorities:[],healthStates:[],ideaStatuses:['New','Under Review','Planned','Implemented','Closed']};
function emptyDb(){return{schemaVersion:CURRENT_SCHEMA_VERSION,workspace:null,settings:structuredClone(DEFAULT_SETTINGS),team:[],demand:[],allocations:[],ideas:[],configFiles:{}}}
let db=emptyDb(),workspaceHandle=null,selectedDemandId=null,activity=[],configDirty=false;
const dirtyRecords={demand:new Set(),team:new Set(),allocations:new Set(),ideas:new Set()},deletedDemand=new Set(),deletedTeam=new Set(),deletedAllocations=new Set(),deletedIdeas=new Set();
const gridState={demand:{editing:false,draft:null,deleted:new Set(),filters:{},sort:null,direction:null},team:{editing:false,draft:null,deleted:new Set(),filters:{},sort:null,direction:null}};
const allocationState={editing:false,draft:null,deleted:new Set(),filters:{demand:'',person:''},direction:'asc'};
const configState={editing:false,draft:null};
const $=id=>document.getElementById(id),clone=x=>structuredClone(x),person=id=>db.team.find(x=>x.id===id),demandById=id=>db.demand.find(x=>x.id===id),ownerName=d=>d.workPackage?.architectureOwner?(person(d.workPackage.architectureOwner)?.name||d.workPackage.architectureOwner):'Unallocated';
function normalizeMonthStart(value){const v=String(value||'').trim();if(/^\d{4}-\d{2}$/.test(v))return `${v}-01`;if(/^\d{4}-\d{2}-01$/.test(v))return v;return''}
function monthInputValue(value){const v=normalizeMonthStart(value);return v?v.slice(0,7):''}
function addMonths(monthStart,count=1){const v=normalizeMonthStart(monthStart);if(!v)return'';const [y,m]=v.slice(0,7).split('-').map(Number),d=new Date(y,m-1+count,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`}
function monthsBetween(fromMonth,toMonth){const from=normalizeMonthStart(fromMonth),to=normalizeMonthStart(toMonth);if(!from||!to||from>to)return[];const out=[];for(let m=from;m&&m<=to;m=addMonths(m,1))out.push(m);return out}
function planningWindow(){const w=db.settings?.planningWindow||{};return{fromMonth:normalizeMonthStart(w.fromMonth),toMonth:normalizeMonthStart(w.toMonth)}}
function planningPeriods(){const w=planningWindow();return monthsBetween(w.fromMonth,w.toMonth)}
/* Compatibility name retained while older view modules are migrated. It now returns canonical month-start dates. */
const planningMonths=()=>planningPeriods();
const monthLabel=m=>{const v=normalizeMonthStart(m);return v?new Date(`${v}T00:00:00`).toLocaleDateString('en-GB',{month:'short',year:'2-digit'}):(m||'—')};
const isOpenDemand=d=>!/^(complete|completed|closed|cancelled)$/i.test((d.status||'').trim());

/* Browser/device preference for the last workspace connection. The local File System Access
   handle itself remains in IndexedDB; localStorage only records which mode should win at startup. */
const AMO_CONNECTION_PREF_KEY='amo.lastWorkspaceConnection';
let workspaceConnectionGeneration=0;
let workspaceConnectionIntent={token:0,mode:null,detail:''};
function getLastConnectionPreference(){try{const value=JSON.parse(localStorage.getItem(AMO_CONNECTION_PREF_KEY)||'null');return value&&['local','remote'].includes(value.mode)?value:null}catch(_){return null}}
function setLastConnectionPreference(value){try{if(value?.mode)localStorage.setItem(AMO_CONNECTION_PREF_KEY,JSON.stringify({...value,updatedAt:new Date().toISOString()}))}catch(_){}return value}
function beginWorkspaceConnection(mode,detail=''){workspaceConnectionGeneration+=1;workspaceConnectionIntent={token:workspaceConnectionGeneration,mode,detail};return workspaceConnectionGeneration}
function workspaceConnectionIsCurrent(token,mode=null){return token===workspaceConnectionIntent.token&&(!mode||workspaceConnectionIntent.mode===mode)}
function renderWorkspaceConnectionBadge(){const el=$('workspaceConnectionBadge');if(!el)return;const repo=window.workspaceRepository;if(repo?.mode==='remote'){el.textContent=`Remote: ${repo.baseUrl||repo.name||'API workspace'}`;el.title=repo.baseUrl||'Remote API workspace';el.dataset.mode='remote';return}if(repo?.mode==='local'&&workspaceHandle){el.textContent=`Local: ${workspaceHandle.name||'Workspace'}`;el.title='Local browser folder. Browsers do not expose the full filesystem path to web applications.';el.dataset.mode='local';return}el.textContent='No workspace open';el.title='No workspace is currently connected.';el.dataset.mode='none'}

function log(m){activity.unshift(`${new Date().toLocaleTimeString()}  ${m}`);activity=activity.slice(0,100);$('activityLog').textContent=activity.join('\n')}
function dirtyCount(){return Object.values(dirtyRecords).reduce((n,s)=>n+s.size,0)+deletedDemand.size+deletedTeam.size+deletedAllocations.size+deletedIdeas.size+(configDirty?1:0)}
function updateBanner(){const dirty=dirtyCount()>0,loaded=!!workspaceHandle;$('stateDot').className='state-dot'+(loaded?' connected':'')+(dirty?' dirty':'');$('workspaceState').textContent=loaded?`${db.workspace?.name||workspaceHandle.name}${dirty?' — saving changes…':''}`:'No workspace loaded — open a data source folder to begin';$('recordSummary').textContent=loaded?`${db.demand.length} demand · ${db.team.length} team · ${db.allocations.length} allocations · ${db.ideas.length} ideas`:'No data loaded';$('saveWorkspaceBtn').disabled=!loaded;$('exportBtn').disabled=!loaded;$('newDemandBtn').disabled=!loaded;$('datasetPill').textContent=loaded?(window.workspaceRepository?.mode==='remote'?'Remote workspace':'Folder workspace'):'No workspace loaded';$('dirtySummary').textContent=dirty?`${dirtyRecords.demand.size} demand changes, ${dirtyRecords.team.size} team changes, ${dirtyRecords.allocations.size} allocation changes, ${dirtyRecords.ideas.size} idea changes${configDirty?', configuration changed':''}; deletions: ${deletedDemand.size} demand, ${deletedTeam.size} team, ${deletedAllocations.size} allocations, ${deletedIdeas.size} ideas. Autosave pending.`:'No unsaved changes.';renderWorkspaceConnectionBadge()}
function markDirty(type,id,msg){dirtyRecords[type].add(id);updateBanner();if(msg)log(msg);if(typeof requestAutosave==='function')requestAutosave()}
function clearDirty(){Object.values(dirtyRecords).forEach(s=>s.clear());deletedDemand.clear();deletedTeam.clear();deletedAllocations.clear();deletedIdeas.clear();configDirty=false;updateBanner()}

/* Legacy low-level helpers remain temporarily for compatibility with UI extensions that have not yet
   been moved to named repository capabilities. Core workspace open/save no longer uses them. */
async function getDirHandle(root,pathParts,create=false){let dir=root;for(const p of pathParts)dir=await dir.getDirectoryHandle(p,{create});return dir}
async function readJson(root,path){let dir=root;for(let i=0;i<path.length-1;i++)dir=await dir.getDirectoryHandle(path[i]);const fh=await dir.getFileHandle(path[path.length-1]),file=await fh.getFile();return JSON.parse(await file.text())}
async function writeJson(root,path,obj){let dir=root;for(let i=0;i<path.length-1;i++)dir=await dir.getDirectoryHandle(path[i],{create:true});const fh=await dir.getFileHandle(path[path.length-1],{create:true}),w=await fh.createWritable();await w.write(JSON.stringify(obj,null,2)+'\n');await w.close()}
async function deleteFileIfExists(root,path){try{let dir=root;for(let i=0;i<path.length-1;i++)dir=await dir.getDirectoryHandle(path[i]);await dir.removeEntry(path[path.length-1])}catch(e){if(e.name!=='NotFoundError')throw e}}
async function listJson(root,pathParts){const dir=await getDirHandle(root,pathParts),rows=[];for await(const [name,h]of dir.entries())if(h.kind==='file'&&name.endsWith('.json')){const f=await h.getFile();rows.push(JSON.parse(await f.text()))}return rows}
function workspaceRepositoryFor(handle=workspaceHandle){if(window.workspaceRepository?.handle===handle)return window.workspaceRepository;if(typeof LocalWorkspaceRepository==='function'&&handle)return new LocalWorkspaceRepository(handle);return null}
function repositorySettings(){return window.workspaceRepository?.getSettings?.()}
function repositorySaveSettings(settings){return window.workspaceRepository?.saveSettings?.(settings)}

function normalizeInitiatives(values){return(values||[]).map(v=>typeof v==='string'?{name:v,businessArea:''}:{name:String(v?.name||''),businessArea:String(v?.businessArea||'')}).filter(v=>v.name)}
function initiativesForBusinessArea(area){return normalizeInitiatives(db.settings.initiatives||[]).filter(i=>!i.businessArea||i.businessArea===area)}
function getPath(o,path){return path.split('.').reduce((a,k)=>a?.[k],o)}function setPath(o,path,v){const p=path.split('.');let x=o;for(let i=0;i<p.length-1;i++)x=x[p[i]]??=(Number.isInteger(+p[i+1])?[]:{});x[p.at(-1)]=v}
function mergeSettings(base,patch){const out=clone(base);for(const[k,v]of Object.entries(patch||{}))out[k]=clone(v);return out}
function totalForecastFte(rows){return(rows||[]).reduce((total,a)=>total+Object.values(a.forecast||{}).reduce((n,v)=>n+(Number(v)||0),0),0)}
function canonicalizeForecast(forecast){const out={};for(const[key,value]of Object.entries(forecast||{})){const month=normalizeMonthStart(key);if(!month)continue;if(Object.prototype.hasOwnProperty.call(out,month)&&Number(out[month])!==Number(value))throw new Error(`Allocation contains conflicting values for ${month}.`);out[month]=value}return out}
function migrateWorkspaceBundle(rawBundle){const bundle=clone(rawBundle),settings=bundle.configFiles?.['settings.json']||bundle.settings||{},version=Number(settings.schemaVersion||1);if(version>CURRENT_SCHEMA_VERSION)throw new Error(`Workspace schema ${version} is newer than this application supports (${CURRENT_SCHEMA_VERSION}).`);let changed=false,migration=null;if(version<2){const months=[...new Set((settings.planningMonths||[]).map(normalizeMonthStart).filter(Boolean))].sort();if(!months.length)throw new Error('Legacy Planning Months is empty; cannot derive a planning window.');const before=totalForecastFte(bundle.allocations);bundle.allocations=(bundle.allocations||[]).map(a=>({...a,forecast:canonicalizeForecast(a.forecast)}));const after=totalForecastFte(bundle.allocations);if(Math.abs(before-after)>1e-9)throw new Error('Allocation FTE changed during planning-window migration.');delete settings.planningMonths;settings.planningWindow={fromMonth:months[0],toMonth:months.at(-1)};settings.schemaVersion=2;bundle.schemaVersion=2;changed=true;migration={fromVersion:version,toVersion:2,planningWindow:clone(settings.planningWindow)}}else{const w=settings.planningWindow||{};const normalized={fromMonth:normalizeMonthStart(w.fromMonth),toMonth:normalizeMonthStart(w.toMonth)};if(normalized.fromMonth!==w.fromMonth||normalized.toMonth!==w.toMonth){settings.planningWindow=normalized;changed=true}const allocations=(bundle.allocations||[]).map(a=>({...a,forecast:canonicalizeForecast(a.forecast)}));if(JSON.stringify(allocations)!==JSON.stringify(bundle.allocations||[])){bundle.allocations=allocations;changed=true}}
  if(!settings.financialPlanning||typeof settings.financialPlanning!=='object'){settings.financialPlanning={roleDayRates:{}};changed=true}
  bundle.configFiles=bundle.configFiles||{};bundle.configFiles['settings.json']=settings;bundle.settings=settings;return{bundle,changed,migration}}
function prepareLoadedWorkspace(rawBundle){const result=migrateWorkspaceBundle(rawBundle);const b=result.bundle;return{...result,db:{schemaVersion:Number(b.configFiles?.['settings.json']?.schemaVersion||b.schemaVersion||CURRENT_SCHEMA_VERSION),workspace:b.workspace,settings:b.configFiles?.['settings.json']||clone(DEFAULT_SETTINGS),team:b.team||[],demand:b.demand||[],allocations:b.allocations||[],ideas:b.ideas||[],configFiles:b.configFiles||{}}}}
function applyMigrationDirtyState(result){if(!result.changed)return;configDirty=true;for(const a of result.db.allocations)dirtyRecords.allocations.add(a.id)}