const CONFIG_SECTIONS=[
  {key:'planningMonths',label:'Planning Months',description:'Ordered monthly planning periods used consistently across Allocations, Resource Plan, Dashboard and Roadmap. Use YYYY-MM format.',required:true,format:'month'},
  {key:'businessAreas',label:'Business Areas',description:'Departments or business functions that initiate Architecture demand.',required:true,reference:{field:'businessArea',label:'Business Area'}},
  {key:'initiatives',label:'Initiatives',description:'Optional major programmes or initiatives that Demand items may be associated with.',required:false,reference:{field:'initiative',label:'Initiative',optional:true}},
  {key:'services',label:'Service Offerings',description:'Architecture services available for Demand classification.',required:true,reference:{field:'service',label:'Service'}},
  {key:'statuses',label:'Demand Statuses',description:'Lifecycle states used by Demand items.',required:true,reference:{field:'status',label:'Status'}},
  {key:'priorities',label:'Priorities',description:'Priority values available on Demand items.',required:true,reference:{field:'priority',label:'Priority'}},
  {key:'healthStates',label:'Health States',description:'Portfolio health values used for Demand reporting.',required:true,reference:{field:'health',label:'Health'}}
];
function cleanConfigValues(values){return values.map(v=>String(v??'').trim()).filter(Boolean)}
function configValues(key){return configState.editing?(configState.draft?.[key]||[]):(db.settings?.[key]||[])}
function renderConfig(){const toolbar=$('configToolbar'),content=$('configContent');if(!toolbar||!content)return;if(!workspaceHandle){toolbar.innerHTML='';content.innerHTML='<div class="notice">Open a workspace folder to view or edit configuration.</div>';return}toolbar.innerHTML=configState.editing?'<button class="btn success" id="saveConfig">Save Changes</button><button class="btn" id="cancelConfig">Cancel</button>':'<button class="btn primary" id="editConfig">Edit Lists</button>';content.innerHTML=`<div class="config-grid">${CONFIG_SECTIONS.map(section=>renderConfigSection(section)).join('')}</div>`;$('editConfig')?.addEventListener('click',()=>{configState.editing=true;configState.draft=Object.fromEntries(CONFIG_SECTIONS.map(s=>[s.key,clone(db.settings[s.key]||[])]));renderConfig()});$('cancelConfig')?.addEventListener('click',()=>{configState.editing=false;configState.draft=null;renderConfig()});$('saveConfig')?.addEventListener('click',saveConfigChanges);content.querySelectorAll('[data-config-add]').forEach(btn=>btn.addEventListener('click',()=>openRecordModal('config',null,'edit',{configKey:btn.dataset.configKey})));content.querySelectorAll('[data-config-row]').forEach(row=>row.addEventListener('dblclick',e=>{if(e.target.closest('button,input,select,textarea'))return;openRecordModal('config',`config:${row.dataset.configKey}:${row.dataset.configIndex}`,'view',{configKey:row.dataset.configKey,configIndex:Number(row.dataset.configIndex)})}));if(configState.editing){content.querySelectorAll('[data-config-input]').forEach(input=>input.addEventListener('input',e=>{const key=e.target.dataset.configKey,index=Number(e.target.dataset.configIndex);configState.draft[key][index]=e.target.value}));content.querySelectorAll('[data-config-delete]').forEach(btn=>btn.addEventListener('click',()=>{const key=btn.dataset.configKey,index=Number(btn.dataset.configIndex);configState.draft[key].splice(index,1);renderConfig()}))}}
function renderConfigSection(section){const values=configValues(section.key);return `<div class="card config-card"><div class="section-title" style="margin-top:0"><div><h2>${section.label}</h2><p class="muted config-description">${section.description}</p></div><button class="btn" data-config-add data-config-key="${section.key}">+ Add</button></div><div class="config-list">${values.length?values.map((value,index)=>`<div class="config-row" data-config-row data-config-key="${section.key}" data-config-index="${index}">${configState.editing?`<input class="cell-input" ${section.format==='month'?'type="month"':''} data-config-input data-config-key="${section.key}" data-config-index="${index}" value="${String(value).replaceAll('&','&amp;').replaceAll('"','&quot;')}"><button class="btn danger" data-config-delete data-config-key="${section.key}" data-config-index="${index}">Delete</button>`:`<span>${section.format==='month'?monthLabel(value):value}</span>`}</div>`).join(''):`<div class="muted">No values configured.</div>`}</div></div>`}
function saveConfigChanges(){const next={};for(const section of CONFIG_SECTIONS){const values=cleanConfigValues(configState.draft[section.key]||[]);if(section.required&&!values.length){alert(`${section.label} must contain at least one value.`);return}const normalized=values.map(v=>v.toLowerCase());if(new Set(normalized).size!==normalized.length){alert(`${section.label} contains duplicate values.`);return}if(section.format==='month'&&values.some(v=>!/^\d{4}-\d{2}$/.test(v))){alert('Planning Months must use YYYY-MM format.');return}next[section.key]=values}if(!next.services.includes('Strategy')){alert('Service Offerings must include Strategy.');return}for(const section of CONFIG_SECTIONS){if(!section.reference)continue;const used=[...new Set(db.demand.map(d=>String(d[section.reference.field]??'').trim()).filter(v=>v||!section.reference.optional))];const missing=used.filter(v=>v&&!next[section.key].includes(v));if(missing.length){alert(`Cannot save ${section.label}. Existing Demand items still use: ${missing.join(', ')}`);return}}db.settings={...db.settings,...next};db.configFiles['settings.json']=clone(db.settings);configDirty=true;configState.editing=false;configState.draft=null;updateBanner();log('Configuration changes committed. Save Workspace to persist settings.json.');refreshAll()}
