const CURRENT_YEAR=new Date().getFullYear();
const YEAR_MONTHS=Array.from({length:12},(_,i)=>`${CURRENT_YEAR}-${String(i+1).padStart(2,'0')}`);
const DEFAULT_SETTINGS={statuses:['Ready / Committed','Mobilising','Analysis / Design','Review & Socialise','Governance','Complete','Cancelled'],services:['Consultancy','Design','Assurance','Strategy'],businessAreas:[],initiatives:[],priorities:['Critical','High','Medium','Low'],healthStates:['Green','Amber','Red']};
function emptyDb(){return{schemaVersion:1,workspace:null,settings:structuredClone(DEFAULT_SETTINGS),team:[],demand:[],allocations:[],configFiles:{}}}
let db=emptyDb(),workspaceHandle=null,selectedDemandId=null,activity=[];
const dirtyRecords={demand:new Set(),team:new Set(),allocations:new Set()},deletedDemand=new Set(),deletedTeam=new Set(),deletedAllocations=new Set();
const gridState={demand:{editing:false,draft:null,deleted:new Set(),filters:{},sort:null,direction:null},team:{editing:false,draft:null,deleted:new Set(),filters:{},sort:null,direction:null}};
const allocationState={editing:false,draft:null,deleted:new Set(),filters:{demand:'',person:''},direction:'asc'};
const $=id=>document.getElementById(id),clone=x=>structuredClone(x),person=id=>db.team.find(x=>x.id===id),demandById=id=>db.demand.find(x=>x.id===id),ownerName=d=>d.workPackage?.architectureOwner?(person(d.workPackage.architectureOwner)?.name||d.workPackage.architectureOwner):'Unallocated';
const monthLabel=m=>new Date(`${m}-01T00:00:00`).toLocaleDateString('en-GB',{month:'short'});
const isOpenDemand=d=>!/^(complete|completed|closed|cancelled)$/i.test((d.status||'').trim());
function log(m){activity.unshift(`${new Date().toLocaleTimeString()}  ${m}`);activity=activity.slice(0,100);$('activityLog').textContent=activity.join('\n')}
function dirtyCount(){return Object.values(dirtyRecords).reduce((n,s)=>n+s.size,0)+deletedDemand.size+deletedTeam.size+deletedAllocations.size}
function updateBanner(){const dirty=dirtyCount()>0,loaded=!!workspaceHandle;$('stateDot').className='state-dot'+(loaded?' connected':'')+(dirty?' dirty':'');$('workspaceState').textContent=loaded?`${db.workspace?.name||workspaceHandle.name}${dirty?' — unsaved changes':''}`:'No workspace loaded — open a data source folder to begin';$('recordSummary').textContent=loaded?`${db.demand.length} demand · ${db.team.length} team · ${db.allocations.length} allocations`:'No data loaded';$('saveWorkspaceBtn').disabled=!loaded;$('exportBtn').disabled=!loaded;$('newDemandBtn').disabled=!loaded;$('datasetPill').textContent=loaded?'Folder workspace':'No workspace loaded';$('dirtySummary').textContent=dirty?`${dirtyRecords.demand.size} demand changes, ${dirtyRecords.team.size} team changes, ${dirtyRecords.allocations.size} allocation changes; deletions: ${deletedDemand.size} demand, ${deletedTeam.size} team, ${deletedAllocations.size} allocations.`:'No unsaved changes.'}
function markDirty(type,id,msg){dirtyRecords[type].add(id);updateBanner();if(msg)log(msg)}function clearDirty(){Object.values(dirtyRecords).forEach(s=>s.clear());deletedDemand.clear();deletedTeam.clear();deletedAllocations.clear();updateBanner()}
async function readJsonFile(h){const f=await h.getFile();return JSON.parse(await f.text())}async function readNamedJson(dir,name,required=false){try{return await readJsonFile(await dir.getFileHandle(name))}catch(e){if(required)throw new Error(`Required file ${name} not found or invalid.`);return null}}
async function readEntityFolder(root,name){const dir=await root.getDirectoryHandle(name),out=[];for await(const [fn,h] of dir.entries())if(h.kind==='file'&&fn.endsWith('.json'))out.push(await readJsonFile(h));return out}
async function readConfigFolder(root){const out={};try{const dir=await root.getDirectoryHandle('config');for await(const [fn,h] of dir.entries())if(h.kind==='file'&&fn.endsWith('.json'))out[fn]=await readJsonFile(h)}catch(e){}return out}
async function writeJson(dir,name,data){const h=await dir.getFileHandle(name,{create:true}),w=await h.createWritable();await w.write(JSON.stringify(data,null,2)+'\n');await w.close()}
async function ensureRW(h){const o={mode:'readwrite'};if(h.queryPermission&&await h.queryPermission(o)==='granted')return true;return h.requestPermission&&await h.requestPermission(o)==='granted'}
async function openWorkspace(){if(!('showDirectoryPicker'in window)){alert('Folder access is not supported in this browser.');return}try{const h=await showDirectoryPicker({mode:'readwrite'}),workspace=await readNamedJson(h,'workspace.json',true);if(workspace.type!=='architecture-operations-hub')throw new Error('Not an Architecture Operations Hub workspace.');const [demand,team,allocations,configFiles]=await Promise.all([readEntityFolder(h,'demand'),readEntityFolder(h,'team'),readEntityFolder(h,'allocations'),readConfigFolder(h)]);workspaceHandle=h;const loadedSettings={...clone(DEFAULT_SETTINGS),...(configFiles['settings.json']||{})};loadedSettings.services=[...new Set([...(loadedSettings.services||[]),'Strategy'])];loadedSettings.businessAreas=loadedSettings.businessAreas||[];loadedSettings.initiatives=loadedSettings.initiatives||[];demand.forEach(d=>{d.businessArea=d.businessArea||'';d.initiative=d.initiative||'';d.costCentreOrProjectCode=d.costCentreOrProjectCode||''});db={schemaVersion:workspace.schemaVersion||1,workspace,settings:loadedSettings,demand,team,allocations,configFiles};clearDirty();selectedDemandId=null;resetEdits();refreshAll();log(`Loaded ${demand.length} demand, ${team.length} team, ${allocations.length} allocations.`)}catch(e){if(e.name!=='AbortError'){alert(e.message);log(`ERROR: ${e.message}`)}}}
async function saveWorkspace(){if(!workspaceHandle)return;try{if(!await ensureRW(workspaceHandle))throw new Error('Read/write permission was not granted.');await writeJson(workspaceHandle,'workspace.json',{...db.workspace,modifiedAt:new Date().toISOString()});for(const [type,folder,rows] of [['demand','demand',db.demand],['team','team',db.team],['allocations','allocations',db.allocations]]){const dir=await workspaceHandle.getDirectoryHandle(folder,{create:true});for(const id of dirtyRecords[type]){const rec=rows.find(x=>x.id===id);if(rec)await writeJson(dir,`${id}.json`,rec)}}for(const [folder,ids] of [['demand',deletedDemand],['team',deletedTeam],['allocations',deletedAllocations]]){if(ids.size){const dir=await workspaceHandle.getDirectoryHandle(folder,{create:true});for(const id of ids){try{await dir.removeEntry(`${id}.json`)}catch(e){if(e.name!=='NotFoundError')throw e}}}}clearDirty();log('Workspace saved successfully.')}catch(e){alert(`Could not save workspace: ${e.message}`);log(`ERROR saving: ${e.message}`)}}
function getPath(o,path){return path.split('.').reduce((v,k)=>v?.[k],o)}function setPath(o,path,value){const p=path.split('.');let x=o;while(p.length>1){const k=p.shift();x[k]=x[k]||{};x=x[k]}x[p[0]]=value}
