(function initActuals(){
  const DEFAULTS={enabled:false,periodFolderPrefix:'Period ',filePrefix:'Oracle YTD Actuals ',fileExtension:'.xlsx',worksheet:'YTD Oracle Download'};
  const REQUIRED_COLUMNS=['Portfolio','Programme','Project Name','Project Number','Month','Person #','Person Name','UOM','QUANTITY','Cost in GBP'];
  const FACT_SCHEMA_VERSION=1,STATE_DB='amo-browser-state',STATE_DB_VERSION=1,STATE_STORE='handles',SOURCE_KEY='actualsFolder';
  let actualsFolderHandle=null,sourceRestorePromise=null;

  function settings(){return{...DEFAULTS,...((typeof db!=='undefined'&&db.settings?.actualsImport)||{})}}
  function normalizeMonth(value){const text=String(value??'').trim(),m=text.match(/^(\d{4})[\/-](\d{1,2})$/);if(!m)return'';return`${m[1]}-${String(Number(m[2])).padStart(2,'0')}`}
  function number(value){if(value===null||value===undefined||value==='')return 0;const n=Number(String(value).replace(/,/g,''));return Number.isFinite(n)?n:0}
  function escRegex(value){return String(value).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
  function parseDateFromName(name,prefix,extension){const rx=new RegExp(`^${escRegex(prefix)}(\\d{2})-(\\d{2})-(\\d{4})${escRegex(extension)}$`,'i'),m=String(name).match(rx);if(!m)return null;const [_,dd,mm,yyyy]=m,date=new Date(Date.UTC(Number(yyyy),Number(mm)-1,Number(dd)));if(date.getUTCFullYear()!==Number(yyyy)||date.getUTCMonth()!==Number(mm)-1||date.getUTCDate()!==Number(dd))return null;return{date,name,iso:`${yyyy}-${mm}-${dd}`}}

  function openStateDb(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window)){reject(new Error('IndexedDB is not available.'));return}const req=indexedDB.open(STATE_DB,STATE_DB_VERSION);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STATE_STORE))req.result.createObjectStore(STATE_STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('Could not open browser state storage.'))})}
  async function stateGet(){try{const idb=await openStateDb();try{return await new Promise((resolve,reject)=>{const req=idb.transaction(STATE_STORE,'readonly').objectStore(STATE_STORE).get(SOURCE_KEY);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})}finally{idb.close()}}catch{return null}}
  async function statePut(handle){if(!handle)return;const idb=await openStateDb();try{await new Promise((resolve,reject)=>{const tx=idb.transaction(STATE_STORE,'readwrite');tx.objectStore(STATE_STORE).put(handle,SOURCE_KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{idb.close()}}
  async function restoreSource(){if(actualsFolderHandle)return actualsFolderHandle;if(!sourceRestorePromise)sourceRestorePromise=stateGet().then(async handle=>{if(!handle)return null;try{if(handle.queryPermission&&await handle.queryPermission({mode:'read'})!=='granted')return null}catch{return null}actualsFolderHandle=handle;window.dispatchEvent(new CustomEvent('amo:actuals-source-changed',{detail:{name:handle.name}}));return handle});return sourceRestorePromise}

  async function discoverLatestSource(folderHandle,config=settings()){
    if(!folderHandle)throw new Error('Choose an Actuals folder first.');const periodRx=new RegExp(`^${escRegex(config.periodFolderPrefix)}(\\d+)$`,'i'),periodFolders=[];
    for await(const [name,handle] of folderHandle.entries()){if(handle.kind!=='directory')continue;const m=name.match(periodRx);if(m)periodFolders.push({name,handle,period:Number(m[1])})}
    if(!periodFolders.length)throw new Error(`No folders matching ${config.periodFolderPrefix}# were found.`);periodFolders.sort((a,b)=>b.period-a.period);const latest=periodFolders[0],files=[];
    for await(const [name,handle] of latest.handle.entries()){if(handle.kind!=='file')continue;const parsed=parseDateFromName(name,config.filePrefix,config.fileExtension);if(parsed)files.push({...parsed,handle})}
    if(!files.length)throw new Error(`No ${config.filePrefix}dd-mm-yyyy${config.fileExtension} file was found in ${latest.name}.`);files.sort((a,b)=>b.date-a.date);const selected=files[0],file=await selected.handle.getFile();return{period:latest.period,periodFolder:latest.name,fileName:selected.name,fileDate:selected.iso,lastModified:file.lastModified,size:file.size,file,warning:files.length>1?`${latest.name} contains ${files.length} matching Actuals files; the latest dated file was selected.`:''}
  }

  function createAggregator(){
    const facts=new Map(),months=new Set();let sourceRows=0,totalHours=0,totalCostGbp=0,skippedInvalidMonth=0,skippedMissingProject=0;
    function add(get){sourceRows++;const month=normalizeMonth(get('Month'));if(!month){skippedInvalidMonth++;return}const projectNumber=String(get('Project Number')??'').trim();if(!projectNumber){skippedMissingProject++;return}const rawPerson=get('Person #'),personNumber=rawPerson===null||rawPerson===undefined||String(rawPerson).trim()===''?null:String(rawPerson).trim(),key=`${month}\u001f${projectNumber}\u001f${personNumber??''}`;let fact=facts.get(key);if(!fact){fact={month,portfolio:String(get('Portfolio')??'').trim(),programme:String(get('Programme')??'').trim()||null,projectNumber,projectName:String(get('Project Name')??'').trim(),personNumber,personName:String(get('Person Name')??'').trim()||null,actualHours:0,actualCostGbp:0};facts.set(key,fact)}const cost=number(get('Cost in GBP'));fact.actualCostGbp+=cost;totalCostGbp+=cost;if(String(get('UOM')??'').trim().toLowerCase()==='hours'){const hours=number(get('QUANTITY'));fact.actualHours+=hours;totalHours+=hours}months.add(month)}
    function result(){const list=[...facts.values()].map(f=>({...f,actualHours:Number(f.actualHours.toFixed(6)),actualCostGbp:Number(f.actualCostGbp.toFixed(2))})).sort((a,b)=>a.month.localeCompare(b.month)||a.projectNumber.localeCompare(b.projectNumber)||String(a.personNumber??'').localeCompare(String(b.personNumber??''))),sortedMonths=[...months].sort();return{facts:list,sourceRows,totalHours:Number(totalHours.toFixed(6)),totalCostGbp:Number(totalCostGbp.toFixed(2)),firstMonth:sortedMonths[0]||null,latestMonth:sortedMonths.at(-1)||null,skippedInvalidMonth,skippedMissingProject}}
    return{add,result}
  }
  function aggregateRows(rows){const header=(rows[0]||[]).map(v=>String(v??'').trim()),index=Object.fromEntries(header.map((v,i)=>[v,i])),missing=REQUIRED_COLUMNS.filter(c=>index[c]===undefined);if(missing.length)throw new Error(`Actuals worksheet is missing required columns: ${missing.join(', ')}`);const agg=createAggregator();for(let r=1;r<rows.length;r++){const row=rows[r];if(!row||row.every(v=>v===null||v===''))continue;agg.add(name=>row[index[name]])}return agg.result()}
  function aggregateWorksheet(ws){
    const range=window.XLSX.utils.decode_range(ws['!ref']||'A1:A1'),cell=(r,c)=>{const entry=Array.isArray(ws)?ws[r]?.[c]:ws[window.XLSX.utils.encode_cell({r,c})];return entry?.v??null},index={};for(let c=range.s.c;c<=range.e.c;c++){const name=String(cell(range.s.r,c)??'').trim();if(name)index[name]=c}const missing=REQUIRED_COLUMNS.filter(name=>index[name]===undefined);if(missing.length)throw new Error(`Actuals worksheet is missing required columns: ${missing.join(', ')}`);const agg=createAggregator();for(let r=range.s.r+1;r<=range.e.r;r++){let populated=false;for(const name of REQUIRED_COLUMNS){const v=cell(r,index[name]);if(v!==null&&v!==''){populated=true;break}}if(!populated)continue;agg.add(name=>cell(r,index[name]))}return agg.result()
  }
  function aggregateWorkbook(arrayBuffer,worksheetName){if(!window.XLSX)throw new Error('Excel parser is not available. Check the application can load its XLSX dependency.');const wb=window.XLSX.read(arrayBuffer,{type:'array',cellDates:false,dense:true});if(wb.SheetNames[0]!==worksheetName)throw new Error(`Expected first worksheet "${worksheetName}", found "${wb.SheetNames[0]||'none'}".`);const ws=wb.Sheets[worksheetName];if(!ws)throw new Error(`Worksheet "${worksheetName}" was not found.`);return aggregateWorksheet(ws)}

  async function readStored(){const repo=window.workspaceRepository;if(!repo?.readActuals)return{factsDocument:null,manifest:null};return{factsDocument:await repo.readActuals(),manifest:await repo.readActualsManifest()}}
  async function refresh({force=false}={}){
    const repo=window.workspaceRepository;if(repo?.mode!=='local')throw new Error('Actuals import is currently available for Local Workspaces only.');const config=settings();if(!config.enabled&&!force)throw new Error('Actuals import is disabled in Settings.');await restoreSource();const source=await discoverLatestSource(actualsFolderHandle,config),existing=await repo.readActualsManifest();if(!force&&existing?.source&&existing.source.period===source.period&&existing.source.fileName===source.fileName&&existing.source.lastModified===source.lastModified&&existing.source.size===source.size)return{changed:false,manifest:existing};
    const agg=aggregateWorkbook(await source.file.arrayBuffer(),config.worksheet),completedAt=new Date().toISOString(),factsDocument={schemaVersion:FACT_SCHEMA_VERSION,facts:agg.facts},warnings=[source.warning,agg.skippedInvalidMonth?`${agg.skippedInvalidMonth} source row(s) were skipped because Month was invalid.`:'',agg.skippedMissingProject?`${agg.skippedMissingProject} source row(s) were skipped because Project Number was blank.`:''].filter(Boolean),manifest={schemaVersion:FACT_SCHEMA_VERSION,source:{period:source.period,periodFolder:source.periodFolder,fileName:source.fileName,fileDate:source.fileDate,worksheet:config.worksheet,lastModified:source.lastModified,size:source.size},import:{completedAt,sourceRows:agg.sourceRows,factRows:agg.facts.length,firstMonth:agg.firstMonth,latestMonth:agg.latestMonth},totals:{hours:agg.totalHours,costGbp:agg.totalCostGbp},warnings};await repo.saveActualsSnapshot(factsDocument,manifest);window.dispatchEvent(new CustomEvent('amo:actuals-updated',{detail:{manifest}}));return{changed:true,manifest,factsDocument}
  }
  async function refreshIfNeeded(){if(!settings().enabled||window.workspaceRepository?.mode!=='local')return null;await restoreSource();if(!actualsFolderHandle)return null;return refresh({force:false})}
  async function clear(){const repo=window.workspaceRepository;if(!repo?.clearActuals)throw new Error('No workspace is open.');await repo.clearActuals();window.dispatchEvent(new CustomEvent('amo:actuals-updated',{detail:{manifest:null}}))}
  async function chooseFolder(){if(!window.showDirectoryPicker)throw new Error('This browser does not support local folder access.');actualsFolderHandle=await window.showDirectoryPicker({mode:'read'});await statePut(actualsFolderHandle);window.dispatchEvent(new CustomEvent('amo:actuals-source-changed',{detail:{name:actualsFolderHandle.name}}));return actualsFolderHandle}
  function sourceName(){return actualsFolderHandle?.name||''}
  window.Actuals={DEFAULTS,REQUIRED_COLUMNS,settings,normalizeMonth,parseDateFromName,aggregateRows,aggregateWorksheet,discoverLatestSource,readStored,refresh,refreshIfNeeded,clear,chooseFolder,restoreSource,sourceName,setFolderHandle:handle=>{actualsFolderHandle=handle}};restoreSource().catch(()=>{});
})();
