function allocationFor(memberId,month){return db.allocations.filter(a=>a.teamMemberId===memberId).reduce((n,a)=>n+(Number(a.forecast?.[month])||0),0)}
function nextAllocationId(rows){const max=Math.max(0,...rows.map(a=>Number((a.id||'').match(/(\d+)$/)?.[1]||0)));return`ALLOC-${CURRENT_YEAR}-${String(max+1).padStart(4,'0')}`}
function makeBlankAllocation(demandId,tempId,teamMemberId=''){return{id:tempId,demandId,teamMemberId,forecast:Object.fromEntries(planningMonths().map(m=>[m,0])),version:1,_draft:true}}
function ensureOwnerDraftRows(){}
function allocationGroups(){
  const source=allocationState.editing?allocationState.draft:db.allocations,demandFilter=String(allocationState.filters.demand||'').toLowerCase(),personFilter=String(allocationState.filters.person||'').toLowerCase();
  let demands=db.demand.filter(isOpenDemand).filter(d=>!demandFilter||`${d.id} ${d.title}`.toLowerCase().includes(demandFilter));
  demands=[...demands].sort((a,b)=>String(a.id).localeCompare(String(b.id),undefined,{numeric:true,sensitivity:'base'}));if(allocationState.direction==='desc')demands.reverse();
  return demands.map(d=>{let allocations=source.filter(a=>a.demandId===d.id&&!allocationState.deleted.has(a.id));if(personFilter)allocations=allocations.filter(a=>(person(a.teamMemberId)?.name||'').toLowerCase().includes(personFilter));return{demand:d,allocations}}).filter(g=>!personFilter||g.allocations.length)
}
function allocationRows(){return allocationGroups().flatMap(g=>g.allocations.map(allocation=>({allocation,demand:g.demand,placeholder:false})))}
function addAllocationForDemand(demandId){if(!allocationState.editing)return;const a=makeBlankAllocation(demandId,nextAllocationId([...db.allocations,...allocationState.draft]));allocationState.draft.push(a);renderAllocations();requestAnimationFrame(()=>document.querySelector(`[data-aid="${CSS.escape(a.id)}"] .alloc-resource-input`)?.focus())}
function availableAllocationResources(){return db.team.filter(t=>t.active!==false)}
function allocationResourceCombo(a){const current=person(a.teamMemberId),name=current?.name||'';return`<div class="alloc-combobox"><input class="cell-input alloc-resource-input" type="text" autocomplete="off" role="combobox" aria-autocomplete="list" aria-expanded="false" placeholder="Type to find resource…" data-aid="${escHtml(a.id)}" data-demand="${escHtml(a.demandId)}" data-selected-id="${escHtml(a.teamMemberId||'')}" value="${escHtml(name)}"><div class="alloc-combo-list" role="listbox"></div></div>`}
function resourceComboMatches(query){const q=String(query||'').trim().toLowerCase();return availableAllocationResources().filter(r=>!q||String(r.name||'').toLowerCase().includes(q))}
function renderResourceComboList(input){const list=input.parentElement?.querySelector('.alloc-combo-list');if(!list)return;const matches=resourceComboMatches(input.value);list.innerHTML=matches.length?matches.map(r=>`<button type="button" role="option" class="alloc-combo-option" data-resource-id="${escHtml(r.id)}"><strong>${escHtml(r.name)}</strong>${r.role?`<span>${escHtml(r.role)}</span>`:''}</button>`).join(''):'<div class="alloc-combo-empty">No matching resources</div>';list.classList.add('open');input.setAttribute('aria-expanded','true');list.querySelectorAll('[data-resource-id]').forEach(btn=>btn.addEventListener('mousedown',e=>{e.preventDefault();selectAllocationResource(input,btn.dataset.resourceId)}))}
function closeResourceCombo(input,restore=false){const list=input.parentElement?.querySelector('.alloc-combo-list');list?.classList.remove('open');input.setAttribute('aria-expanded','false');if(restore){const a=allocationState.draft?.find(x=>x.id===input.dataset.aid);input.value=person(a?.teamMemberId)?.name||'';input.dataset.selectedId=a?.teamMemberId||''}}
function selectAllocationResource(input,resourceId){const a=allocationState.draft?.find(x=>x.id===input.dataset.aid),r=availableAllocationResources().find(x=>x.id===resourceId);if(!a||!r)return;const wasBlank=!a.teamMemberId;a.teamMemberId=r.id;if(wasBlank)planningMonths().forEach(m=>a.forecast[m]=0);input.dataset.selectedId=r.id;input.value=r.name;closeResourceCombo(input,false);renderAllocations();requestAnimationFrame(()=>document.querySelector(`[data-aid="${CSS.escape(a.id)}"] .alloc-resource-input`)?.focus())}
function bindAllocationResourceCombos(){document.querySelectorAll('#allocationTable .alloc-resource-input').forEach(input=>{input.addEventListener('focus',()=>renderResourceComboList(input));input.addEventListener('input',()=>{input.dataset.selectedId='';renderResourceComboList(input)});input.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closeResourceCombo(input,true);return}if(e.key==='Enter'){const first=input.parentElement?.querySelector('[data-resource-id]');if(first){e.preventDefault();selectAllocationResource(input,first.dataset.resourceId)}return}if(e.key==='ArrowDown'){const first=input.parentElement?.querySelector('[data-resource-id]');if(first){e.preventDefault();first.focus()}}});input.addEventListener('blur',()=>setTimeout(()=>{if(!input.dataset.selectedId)closeResourceCombo(input,true);else closeResourceCombo(input,false)},120));const list=input.parentElement?.querySelector('.alloc-combo-list');list?.addEventListener('keydown',e=>{const option=e.target.closest('[data-resource-id]');if(!option)return;if(e.key==='Enter'||e.key===' '){e.preventDefault();selectAllocationResource(input,option.dataset.resourceId)}if(e.key==='Escape'){e.preventDefault();input.focus();closeResourceCombo(input,true)}})})}
function renderAllocations(){
  const months=planningMonths(),groups=allocationGroups(),editing=allocationState.editing,allocationCount=groups.reduce((n,g)=>n+g.allocations.length,0);
  $('allocationToolbar').innerHTML=editing?'<button class="btn success" id="saveAllocations">Save Changes</button><button class="btn" id="cancelAllocations">Cancel</button><button class="btn" id="clearAllocationFilters">Clear Filters</button>':`<button class="btn" id="editAllocations" ${workspaceHandle?'':'disabled'}>Edit List</button><button class="btn" id="clearAllocationFilters">Clear Filters</button>`;
  $('allocationCount').textContent=workspaceHandle?`Showing ${allocationCount} allocation${allocationCount===1?'':'s'} across ${groups.length} demand item${groups.length===1?'':'s'}`:'No workspace loaded';
  const colspan=1+months.length+(editing?1:0);
  const body=groups.map(({demand:d,allocations})=>{
    const header=`<tr class="allocation-demand-header" data-demand-header="${d.id}"><td colspan="${colspan}"><div class="allocation-demand-heading"><div><span class="allocation-demand-id">${escHtml(d.id)}</span><strong class="allocation-demand-title">${escHtml(d.title)}</strong></div>${editing?`<button class="btn allocation-add" type="button" data-add-allocation="${d.id}">＋ New Allocation</button>`:''}</div></td></tr>`;
    const rows=allocations.map(a=>`<tr class="allocation-row${!a.teamMemberId?' allocation-inactive':''}" data-aid="${a.id}" data-demand="${d.id}">${editing?`<td class="allocation-remove-cell"><button class="allocation-remove" type="button" data-remove-allocation="${a.id}" title="Remove allocation" aria-label="Remove allocation">−</button></td>`:''}<td class="allocation-resource">${editing?allocationResourceCombo(a):(a.teamMemberId?(person(a.teamMemberId)?.name||a.teamMemberId):'<span class="muted">Unallocated</span>')}</td>${months.map(m=>`<td>${editing?(a.teamMemberId?`<input class="cell-input compact alloc-pct" type="number" min="0" max="100" step="5" data-aid="${a.id}" data-demand="${d.id}" data-month="${m}" value="${Math.round((Number(a.forecast?.[m])||0)*100)}">`:'<span class="muted allocation-empty">—</span>'):(a.teamMemberId?Math.round((Number(a.forecast?.[m])||0)*100)+'%':'—')}</td>`).join('')}</tr>`).join('');
    return header+rows
  }).join('');
  $('allocationTable').innerHTML=`<thead><tr>${editing?'<th class="allocation-remove-head"></th>':''}<th>Resource</th>${months.map(m=>`<th class="month">${monthLabel(m)}</th>`).join('')}</tr><tr class="filter-row">${editing?'<th></th>':''}<th><input id="allocationPersonFilter" value="${escHtml(allocationState.filters.person)}" placeholder="filter resource…"></th>${months.map(()=>'<th></th>').join('')}</tr><tr class="allocation-demand-filter-row"><th colspan="${colspan}"><input id="allocationDemandFilter" value="${escHtml(allocationState.filters.demand)}" placeholder="filter demand ID or title…"></th></tr></thead><tbody>${body}</tbody>`;
  $('editAllocations')?.addEventListener('click',()=>{if(!workspaceHandle)return;allocationState.editing=true;allocationState.draft=clone(db.allocations);allocationState.deleted=new Set();renderAllocations()});
  $('cancelAllocations')?.addEventListener('click',()=>{allocationState.editing=false;allocationState.draft=null;allocationState.deleted=new Set();renderAllocations()});
  $('clearAllocationFilters').onclick=()=>{allocationState.filters={demand:'',person:''};renderAllocations()};
  $('allocationTable').querySelectorAll('[data-add-allocation]').forEach(b=>b.onclick=()=>addAllocationForDemand(b.dataset.addAllocation));
  $('allocationTable').querySelectorAll('tbody tr[data-aid]').forEach(tr=>tr.addEventListener('dblclick',e=>{if(e.target.closest('button,input,select,textarea'))return;openRecordModal('allocation',tr.dataset.aid,'view')}));
  if(editing){
    $('saveAllocations').onclick=saveAllocations;bindAllocationResourceCombos();
    $('allocationTable').querySelectorAll('.alloc-pct').forEach(el=>el.onchange=e=>allocationPctChanged(e.target));
    $('allocationTable').querySelectorAll('[data-remove-allocation]').forEach(el=>el.onclick=e=>{allocationState.deleted.add(e.currentTarget.dataset.removeAllocation);renderAllocations()})
  }
  const bindFilter=(id,key)=>{$(id).addEventListener('input',e=>{clearTimeout(debounceTimers[`alloc-${key}`]);allocationState.filters[key]=e.target.value;const pos=e.target.selectionStart;debounceTimers[`alloc-${key}`]=setTimeout(()=>{renderAllocations();requestAnimationFrame(()=>{const n=$(id);n?.focus();n?.setSelectionRange?.(pos,pos)})},350)})};bindFilter('allocationDemandFilter','demand');bindFilter('allocationPersonFilter','person')
}
function allocationPersonChanged(el){const a=allocationState.draft.find(x=>x.id===el.dataset.aid);if(!a)return;a.teamMemberId=el.value;planningMonths().forEach(m=>a.forecast[m]=el.value?(Number(a.forecast[m])||0):0);renderAllocations()}
function allocationPctChanged(el){const a=allocationState.draft.find(x=>x.id===el.dataset.aid);if(!a)return;a.forecast[el.dataset.month]=Math.max(0,Math.min(100,Number(el.value)||0))/100}
function saveAllocations(){const pending=allocationState.draft.filter(a=>!allocationState.deleted.has(a.id));const invalid=pending.find(a=>!a.teamMemberId||!person(a.teamMemberId));if(invalid){const d=demandById(invalid.demandId);alert(`Select a valid Resource for every allocation${d?` under ${d.id} — ${d.title}`:''}, or remove the incomplete allocation row.`);return}const final=pending,finalIds=new Set(final.map(a=>a.id));for(const old of db.allocations)if(!finalIds.has(old.id))deletedAllocations.add(old.id);for(const id of allocationState.deleted)if(db.allocations.some(a=>a.id===id))deletedAllocations.add(id);const oldMap=new Map(db.allocations.map(a=>[a.id,a]));for(const a of final){const old=oldMap.get(a.id);if(!old||JSON.stringify(old)!==JSON.stringify(a)){dirtyRecords.allocations.add(a.id);a.version=(Number(a.version)||0)+1;a.modifiedAt=new Date().toISOString()}}db.allocations=final.map(a=>{const x=clone(a);delete x._draft;return x});allocationState.editing=false;allocationState.draft=null;allocationState.deleted=new Set();updateBanner();log('Allocation changes committed.');if(typeof requestAutosave==='function')requestAutosave();refreshAll()}
function teamCapacity(){return db.team.filter(t=>t.active!==false).reduce((n,t)=>n+(Number(t.fte)||0),0)}
function allocatedTotal(month){return db.allocations.reduce((n,a)=>n+(Number(a.forecast?.[month])||0),0)}
function unresolvedWithoutAllocation(){return db.demand.filter(isOpenDemand).filter(d=>!db.allocations.some(a=>a.demandId===d.id&&a.teamMemberId))}

(function addNestedAllocationStyles(){if(document.getElementById('nested-allocation-styles'))return;const s=document.createElement('style');s.id='nested-allocation-styles';s.textContent=`
#allocationTable .allocation-demand-header td{padding:7px 10px;background:var(--soft);border-top:2px solid var(--line);border-bottom:1px solid var(--line)}
#allocationTable .allocation-demand-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:28px}
#allocationTable .allocation-demand-heading>div{display:flex;align-items:baseline;gap:9px;min-width:0}
#allocationTable .allocation-demand-id{font-size:.68rem;font-weight:750;color:var(--muted);letter-spacing:.02em;white-space:nowrap}
#allocationTable .allocation-demand-title{font-size:.82rem;color:var(--ink);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
#allocationTable .allocation-add{margin-left:auto;background:transparent;border-color:transparent;color:var(--accent);font-weight:850;white-space:nowrap}
#allocationTable .allocation-add:hover{background:var(--panel)}
#allocationTable .allocation-remove-head,#allocationTable .allocation-remove-cell{width:38px;min-width:38px;max-width:38px;text-align:center;padding-left:5px;padding-right:5px}
#allocationTable .allocation-remove{width:23px;height:23px;border-radius:50%;border:1px solid var(--bad);background:transparent;color:var(--bad);font-size:1rem;font-weight:900;line-height:18px;cursor:pointer;padding:0}
#allocationTable .allocation-remove:hover{background:var(--bad);color:white}
#allocationTable .allocation-row td{border-bottom-color:color-mix(in srgb,var(--line) 65%,transparent)}
#allocationTable .allocation-demand-filter-row th{padding-top:5px;padding-bottom:7px;background:var(--panel)}
#allocationTable .allocation-demand-filter-row input{width:100%;max-width:520px}
#allocationTable .alloc-combobox{position:relative;min-width:210px}
#allocationTable .alloc-resource-input{width:100%}
#allocationTable .alloc-combo-list{display:none;position:absolute;left:0;right:0;top:calc(100% + 3px);max-height:220px;overflow:auto;padding:4px;background:var(--panel);border:1px solid var(--line);border-radius:8px;box-shadow:var(--shadow);z-index:40}
#allocationTable .alloc-combo-list.open{display:block}
#allocationTable .alloc-combo-option{display:flex;width:100%;flex-direction:column;align-items:flex-start;gap:1px;padding:7px 8px;border:0;border-radius:6px;background:transparent;color:var(--ink);text-align:left;cursor:pointer}
#allocationTable .alloc-combo-option:hover,#allocationTable .alloc-combo-option:focus{background:var(--soft);outline:none}
#allocationTable .alloc-combo-option span{font-size:.68rem;color:var(--muted)}
#allocationTable .alloc-combo-empty{padding:8px;color:var(--muted);font-size:.74rem}
html[data-theme="dark"] #allocationTable .allocation-demand-header td{background:#22304a;color:var(--ink)}
html[data-theme="dark"] #allocationTable .alloc-combo-list{background:var(--panel);border-color:var(--line)}
@media(max-width:760px){#allocationTable .allocation-demand-heading{align-items:flex-start}.allocation-demand-heading>div{flex-direction:column;gap:2px}}
`;document.head.appendChild(s)})();
