const CONFIG_SECTIONS=[
  {key:'businessAreas',label:'Business Areas',description:'Departments or business functions that initiate Architecture demand.',required:true,reference:{field:'businessArea',label:'Business Area'}},
  {key:'initiatives',label:'Initiatives',description:'Optional major programmes or initiatives. Every Initiative must belong to one Business Area.',required:false,format:'initiative',reference:{field:'initiative',label:'Initiative',optional:true}},
  {key:'services',label:'Service Offerings',description:'Architecture services available for Demand classification.',required:true,reference:{field:'service',label:'Service'}},
  {key:'statuses',label:'Demand Statuses',description:'Lifecycle states used by Demand items.',required:true,reference:{field:'status',label:'Status'}},
  {key:'priorities',label:'Priorities',description:'Priority values available on Demand items.',required:true,reference:{field:'priority',label:'Priority'}},
  {key:'healthStates',label:'Health States',description:'Portfolio health values used for Demand reporting.',required:true,reference:{field:'health',label:'Health'}}
];
function normalizeInitiatives(values){return(values||[]).map(v=>typeof v==='string'?{name:v,businessArea:''}:{name:String(v?.name||'').trim(),businessArea:String(v?.businessArea||'').trim()}).filter(v=>v.name)}
function initiativeName(v){return typeof v==='string'?v:(v?.name||'')}
function initiativeBusinessArea(v){return typeof v==='object'?(v?.businessArea||''):''}
function initiativesForBusinessArea(area){return normalizeInitiatives(db.settings?.initiatives||[]).filter(i=>i.businessArea===area)}
function cleanConfigValues(values){return values.map(v=>String(v??'').trim()).filter(Boolean)}
function configValues(key){return configState.editing?(configState.draft?.[key]||[]):(db.settings?.[key]||[])}
function planningWindowDraft(){return configState.editing?(configState.draft?.planningWindow||{}):(db.settings?.planningWindow||{})}
function renderPlanningWindowCard(){const w=planningWindowDraft(),from=monthInputValue(w.fromMonth),to=monthInputValue(w.toMonth),periods=monthsBetween(w.fromMonth,w.toMonth);return `<div class="card config-card planning-window-card"><div class="section-title" style="margin-top:0"><div><h2>Planning Window</h2><p class="muted config-description">Controls which continuous monthly periods are shown in planning and reporting views. It does not constrain or remove Demand dates or allocation data outside the window.</p></div></div><div class="config-list"><div class="config-row"><label><strong>From month</strong><br>${configState.editing?`<input class="cell-input" id="planningWindowFrom" type="month" value="${escHtml(from)}">`:`<span>${monthLabel(w.fromMonth)}</span>`}</label><label><strong>To month</strong><br>${configState.editing?`<input class="cell-input" id="planningWindowTo" type="month" value="${escHtml(to)}">`:`<span>${monthLabel(w.toMonth)}</span>`}</label></div><div class="muted">${periods.length?`${periods.length} monthly period${periods.length===1?'':'s'} displayed.`:'No valid planning window configured.'}</div></div></div>`}
function renderConfig(){const toolbar=$('configToolbar'),content=$('configContent');if(!toolbar||!content)return;if(!workspaceHandle){toolbar.innerHTML='';content.innerHTML='<div class="notice">Open a workspace folder to view or edit configuration.</div>';return}toolbar.innerHTML=configState.editing?'<button class="btn success" id="saveConfig">Save Changes</button><button class="btn" id="cancelConfig">Cancel</button>':'<button class="btn primary" id="editConfig">Edit Lists</button>';content.innerHTML=`<div class="config-grid">${renderPlanningWindowCard()}${CONFIG_SECTIONS.map(section=>renderConfigSection(section)).join('')}</div>`;$('editConfig')?.addEventListener('click',()=>{configState.editing=true;configState.draft={planningWindow:clone(db.settings.planningWindow||{}),...Object.fromEntries(CONFIG_SECTIONS.map(s=>[s.key,s.key==='initiatives'?clone(normalizeInitiatives(db.settings[s.key]||[])):clone(db.settings[s.key]||[])]))};renderConfig()});$('cancelConfig')?.addEventListener('click',()=>{configState.editing=false;configState.draft=null;renderConfig()});$('saveConfig')?.addEventListener('click',saveConfigChanges);$('planningWindowFrom')?.addEventListener('input',e=>{configState.draft.planningWindow.fromMonth=normalizeMonthStart(e.target.value)});$('planningWindowTo')?.addEventListener('input',e=>{configState.draft.planningWindow.toMonth=normalizeMonthStart(e.target.value)});content.querySelectorAll('[data-config-add]').forEach(btn=>btn.addEventListener('click',()=>openRecordModal('config',null,'edit',{configKey:btn.dataset.configKey})));content.querySelectorAll('[data-config-row]').forEach(row=>row.addEventListener('dblclick',e=>{if(e.target.closest('button,input,select,textarea'))return;openRecordModal('config',`config:${row.dataset.configKey}:${row.dataset.configIndex}`,'view',{configKey:row.dataset.configKey,configIndex:Number(row.dataset.configIndex)})}));if(configState.editing){content.querySelectorAll('[data-config-input]').forEach(input=>input.addEventListener('input',e=>{const key=e.target.dataset.configKey,index=Number(e.target.dataset.configIndex);configState.draft[key][index]=e.target.value}));content.querySelectorAll('[data-initiative-name]').forEach(input=>input.addEventListener('input',e=>{configState.draft.initiatives[Number(e.target.dataset.initiativeName)].name=e.target.value}));content.querySelectorAll('[data-initiative-area]').forEach(select=>select.addEventListener('change',e=>{configState.draft.initiatives[Number(e.target.dataset.initiativeArea)].businessArea=e.target.value}));content.querySelectorAll('[data-config-delete]').forEach(btn=>btn.addEventListener('click',()=>{const key=btn.dataset.configKey,index=Number(btn.dataset.configIndex);configState.draft[key].splice(index,1);renderConfig()}))}}
function renderConfigSection(section){const values=configValues(section.key);return `<div class="card config-card"><div class="section-title" style="margin-top:0"><div><h2>${section.label}</h2><p class="muted config-description">${section.description}</p></div><button class="btn" data-config-add data-config-key="${section.key}">+ Add</button></div><div class="config-list">${values.length?values.map((value,index)=>renderConfigRow(section,value,index)).join(''):`<div class="muted">No values configured.</div>`}</div></div>`}
function renderConfigRow(section,value,index){if(section.format==='initiative'){const i=typeof value==='string'?{name:value,businessArea:''}:value;return `<div class="config-row" data-config-row data-config-key="initiatives" data-config-index="${index}">${configState.editing?`<select class="cell-input" data-initiative-area="${index}"><option value="">Select Business Area…</option>${(db.settings.businessAreas||[]).map(a=>`<option value="${escHtml(a)}" ${a===i.businessArea?'selected':''}>${escHtml(a)}</option>`).join('')}</select><input class="cell-input" data-initiative-name="${index}" value="${escHtml(i.name||'')}" placeholder="Initiative name"><button class="btn danger" data-config-delete data-config-key="initiatives" data-config-index="${index}">Delete</button>`:`<span><strong>${escHtml(i.name||'')}</strong><br><span class="muted">${escHtml(i.businessArea||'No Business Area assigned')}</span></span>`}</div>`}return `<div class="config-row" data-config-row data-config-key="${section.key}" data-config-index="${index}">${configState.editing?`<input class="cell-input" data-config-input data-config-key="${section.key}" data-config-index="${index}" value="${escHtml(value)}"><button class="btn danger" data-config-delete data-config-key="${section.key}" data-config-index="${index}">Delete</button>`:`<span>${escHtml(value)}</span>`}</div>`}
function saveConfigChanges(){const next={schemaVersion:CURRENT_SCHEMA_VERSION};const from=normalizeMonthStart(configState.draft?.planningWindow?.fromMonth),to=normalizeMonthStart(configState.draft?.planningWindow?.toMonth);if(!from||!to||from>to){alert('Planning Window must have valid From and To months, with From no later than To.');return}next.planningWindow={fromMonth:from,toMonth:to};for(const section of CONFIG_SECTIONS){if(section.format==='initiative'){const values=normalizeInitiatives(configState.draft.initiatives||[]);if(values.some(i=>!i.businessArea)){alert('Every Initiative must have an owning Business Area.');return}if(values.some(i=>!(configState.draft.businessAreas||db.settings.businessAreas||[]).includes(i.businessArea))){alert('Every Initiative must reference a configured Business Area.');return}const names=values.map(i=>i.name.toLowerCase());if(new Set(names).size!==names.length){alert('Initiatives contains duplicate names.');return}next.initiatives=values;continue}const values=cleanConfigValues(configState.draft[section.key]||[]);if(section.required&&!values.length){alert(`${section.label} must contain at least one value.`);return}const normalized=values.map(v=>v.toLowerCase());if(new Set(normalized).size!==normalized.length){alert(`${section.label} contains duplicate values.`);return}next[section.key]=values}if(!next.services.includes('Strategy')){alert('Service Offerings must include Strategy.');return}const initiativeNames=new Set((next.initiatives||[]).map(i=>i.name));for(const d of db.demand){if(d.initiative&&!initiativeNames.has(d.initiative)){alert(`Cannot save Initiatives. Demand ${d.id} still uses ${d.initiative}.`);return}if(d.initiative){const i=next.initiatives.find(x=>x.name===d.initiative);if(i&&i.businessArea!==d.businessArea){alert(`Cannot save Initiatives. Demand ${d.id} uses ${d.initiative}, which belongs to ${i.businessArea}, not ${d.businessArea}.`);return}}}for(const section of CONFIG_SECTIONS){if(!section.reference||section.key==='initiatives')continue;const used=[...new Set(db.demand.map(d=>String(d[section.reference.field]??'').trim()).filter(v=>v||!section.reference.optional))];const missing=used.filter(v=>v&&!next[section.key].includes(v));if(missing.length){alert(`Cannot save ${section.label}. Existing Demand items still use: ${missing.join(', ')}`);return}}db.settings={...db.settings,...next};delete db.settings.planningMonths;db.configFiles['settings.json']=clone(db.settings);configDirty=true;configState.editing=false;configState.draft=null;updateBanner();log('Configuration changes committed. Autosave scheduled.');if(typeof requestAutosave==='function')requestAutosave();refreshAll()}
