function allocationFor(memberId,month){return db.allocations.filter(a=>a.teamMemberId===memberId).reduce((n,a)=>n+(Number(a.forecast?.[month])||0),0)}
function nextAllocationId(rows){const max=Math.max(0,...rows.map(a=>Number((a.id||'').match(/(\d+)$/)?.[1]||0)));return`ALLOC-${CURRENT_YEAR}-${String(max+1).padStart(4,'0')}`}
function makeBlankAllocation(demandId,tempId,teamMemberId=''){return{id:tempId,demandId,teamMemberId,forecast:Object.fromEntries(planningMonths().map(m=>[m,0])),version:1,_draft:true}}
function ensureOwnerDraftRows(){}
function allocationGroups(){
  const source=allocationState.editing?allocationState.draft:db.allocations,demandFilter=String(allocationState.filters.demand||'').toLowerCase(),personFilter=String(allocationState.filters.person||'').toLowerCase();
  let demands=db.demand.filter(isOpenDemand).filter(d=>!demandFilter||`${d.id} ${d.title}`.toLowerCase().includes(demandFilter));
  demands=[...demands].sort((a,b)=>String(a.id).localeCompare(String(b.id),undefined,{numeric:true,sensitivity:'base'}));if(allocationState.direction==='desc')demands.reverse();
  return demands.map(d=>{let allocations=source.filter(a=>a.demandId===d.id&&!allocationState.deleted.has(a.id));if(personFilter)allocations=allocations.filter(a=>(person(a.teamMemberId)?.name||'').toLowerCase().includes(personFilter));return{demand:d,allocations}}).filter(g=>!personFilter||g.allocations.length)
}
function allocationRows(){return allocationGroups().flatMap(g=>g.allocations.map(allocation=>({allocation,demand:g.demand,placeholder:false})))}
function addAllocationForDemand(demandId){if(!allocationState.editing)return;const a=makeBlankAllocation(demandId,nextAllocationId([...db.allocations,...allocationState.draft]));allocationState.draft.push(a);renderAllocations();requestAnimationFrame(()=>document.querySelector(`[data-aid="${CSS.escape(a.id)}"] .alloc-person`)?.focus())}
function renderAllocations(){
  const months=planningMonths(),groups=allocationGroups(),editing=allocationState.editing,allocationCount=groups.reduce((n,g)=>n+g.allocations.length,0);
  $('allocationToolbar').innerHTML=editing?'<button class="btn success" id="saveAllocations">Save Changes</button><button class="btn" id="cancelAllocations">Cancel</button><button class="btn" id="clearAllocationFilters">Clear Filters</button>':`<button class="btn" id="editAllocations" ${workspaceHandle?'':'disabled'}>Edit List</button><button class="btn" id="clearAllocationFilters">Clear Filters</button>`;
  $('allocationCount').textContent=workspaceHandle?`Showing ${allocationCount} allocation${allocationCount===1?'':'s'} across ${groups.length} demand item${groups.length===1?'':'s'}`:'No workspace loaded';
  const personOpts='<option value="">Select resource…</option>'+db.team.filter(t=>t.active!==false).map(t=>`<option value="${t.id}">${t.name}</option>`).join(''),colspan=2+months.length+(editing?1:0);
  const body=groups.map(({demand:d,allocations})=>{
    const header=`<tr class="allocation-demand-header" data-demand-header="${d.id}"><td colspan="${colspan}"><div class="allocation-demand-heading"><div><span class="allocation-demand-id">${escHtml(d.id)}</span><strong class="allocation-demand-title">${escHtml(d.title)}</strong></div>${editing?`<button class="btn allocation-add" type="button" data-add-allocation="${d.id}">＋ New Allocation</button>`:''}</div></td></tr>`;
    const rows=allocations.map(a=>`<tr class="allocation-row${!a.teamMemberId?' allocation-inactive':''}" data-aid="${a.id}" data-demand="${d.id}">${editing?`<td class="allocation-remove-cell"><button class="allocation-remove" type="button" data-remove-allocation="${a.id}" title="Remove allocation" aria-label="Remove allocation">−</button></td>`:''}<td class="allocation-resource">${editing?`<select class="cell-input alloc-person" data-aid="${a.id}" data-demand="${d.id}">${personOpts.replace(`value="${a.teamMemberId}"`,`value="${a.teamMemberId}" selected`)}</select>`:(a.teamMemberId?(person(a.teamMemberId)?.name||a.teamMemberId):'<span class="muted">Unallocated</span>')}</td>${months.map(m=>`<td>${editing?(a.teamMemberId?`<input class="cell-input compact alloc-pct" type="number" min="0" max="100" step="5" data-aid="${a.id}" data-demand="${d.id}" data-month="${m}" value="${Math.round((Number(a.forecast?.[m])||0)*100)}">`:'<span class="muted allocation-empty">—</span>'):(a.teamMemberId?Math.round((Number(a.forecast?.[m])||0)*100)+'%':'—')}</td>`).join('')}</tr>`).join('');
    return header+rows
  }).join('');
  $('allocationTable').innerHTML=`<thead><tr>${editing?'<th class="allocation-remove-head"></th>':''}<th>Resource</th>${months.map(m=>`<th class="month">${monthLabel(m)}</th>`).join('')}</tr><tr class="filter-row">${editing?'<th></th>':''}<th><input id="allocationPersonFilter" value="${escHtml(allocationState.filters.person)}" placeholder="filter resource…"></th>${months.map(()=>'<th></th>').join('')}</tr><tr class="allocation-demand-filter-row"><th colspan="${colspan}"><input id="allocationDemandFilter" value="${escHtml(allocationState.filters.demand)}" placeholder="filter demand ID or title…"></th></tr></thead><tbody>${body}</tbody>`;
  $('editAllocations')?.addEventListener('click',()=>{if(!workspaceHandle)return;allocationState.editing=true;allocationState.draft=clone(db.allocations);allocationState.deleted=new Set();renderAllocations()});
  $('cancelAllocations')?.addEventListener('click',()=>{allocationState.editing=false;allocationState.draft=null;allocationState.deleted=new Set();renderAllocations()});
  $('clearAllocationFilters').onclick=()=>{allocationState.filters={demand:'',person:''};renderAllocations()};
  $('allocationTable').querySelectorAll('[data-add-allocation]').forEach(b=>b.onclick=()=>addAllocationForDemand(b.dataset.addAllocation));
  $('allocationTable').querySelectorAll('tbody tr[data-aid]').forEach(tr=>tr.addEventListener('dblclick',e=>{if(e.target.closest('button,input,select,textarea'))return;openRecordModal('allocation',tr.dataset.aid,'view')}));
  if(editing){
    $('saveAllocations').onclick=saveAllocations;
    $('allocationTable').querySelectorAll('.alloc-person').forEach(el=>el.onchange=e=>allocationPersonChanged(e.target));
    $('allocationTable').querySelectorAll('.alloc-pct').forEach(el=>el.onchange=e=>allocationPctChanged(e.target));
    $('allocationTable').querySelectorAll('[data-remove-allocation]').forEach(el=>el.onclick=e=>{allocationState.deleted.add(e.currentTarget.dataset.removeAllocation);renderAllocations()})
  }
  const bindFilter=(id,key)=>{$(id).addEventListener('input',e=>{clearTimeout(debounceTimers[`alloc-${key}`]);allocationState.filters[key]=e.target.value;const pos=e.target.selectionStart;debounceTimers[`alloc-${key}`]=setTimeout(()=>{renderAllocations();requestAnimationFrame(()=>{const n=$(id);n?.focus();n?.setSelectionRange?.(pos,pos)})},350)})};bindFilter('allocationDemandFilter','demand');bindFilter('allocationPersonFilter','person')
}
function allocationPersonChanged(el){const a=allocationState.draft.find(x=>x.id===el.dataset.aid);if(!a)return;a.teamMemberId=el.value;planningMonths().forEach(m=>a.forecast[m]=el.value?(Number(a.forecast[m])||0):0);renderAllocations()}
function allocationPctChanged(el){const a=allocationState.draft.find(x=>x.id===el.dataset.aid);if(!a)return;a.forecast[el.dataset.month]=Math.max(0,Math.min(100,Number(el.value)||0))/100}
function saveAllocations(){const final=allocationState.draft.filter(a=>!allocationState.deleted.has(a.id)&&a.teamMemberId),finalIds=new Set(final.map(a=>a.id));for(const old of db.allocations)if(!finalIds.has(old.id))deletedAllocations.add(old.id);for(const id of allocationState.deleted)if(db.allocations.some(a=>a.id===id))deletedAllocations.add(id);const oldMap=new Map(db.allocations.map(a=>[a.id,a]));for(const a of final){const old=oldMap.get(a.id);if(!old||JSON.stringify(old)!==JSON.stringify(a)){dirtyRecords.allocations.add(a.id);a.version=(Number(a.version)||0)+1;a.modifiedAt=new Date().toISOString()}}db.allocations=final.map(a=>{const x=clone(a);delete x._draft;return x});allocationState.editing=false;allocationState.draft=null;allocationState.deleted=new Set();updateBanner();log('Allocation changes committed.');if(typeof requestAutosave==='function')requestAutosave();refreshAll()}
function teamCapacity(){return db.team.filter(t=>t.active!==false).reduce((n,t)=>n+(Number(t.fte)||0),0)}
function allocatedTotal(month){return db.allocations.reduce((n,a)=>n+(Number(a.forecast?.[month])||0),0)}
function unresolvedWithoutAllocation(){return db.demand.filter(isOpenDemand).filter(d=>!db.allocations.some(a=>a.demandId===d.id&&a.teamMemberId))}
