const roadmapState={editing:false,draft:null,drag:null};
function roadmapDemandRows(){return roadmapState.editing?roadmapState.draft:db.demand}
function roadmapHorizon(){const months=planningPeriods();if(!months.length)return null;const first=months[0],[fy,fm]=first.split('-').map(Number),last=months[months.length-1],[ly,lm]=last.split('-').map(Number);return{start:new Date(fy,fm-1,1),end:new Date(ly,lm,1),endExclusive:new Date(ly,lm,1),months}}
function isoDay(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function clampDate(d,min,max){return new Date(Math.max(min.getTime(),Math.min(max.getTime(),d.getTime())))}
function roadmapScaleEnd(h){const [y,m]=h.months[h.months.length-1].split('-').map(Number);return new Date(y,m,1)}
function datePct(value,h){if(!value)return null;const d=new Date(`${value}T00:00:00`),scaleEnd=roadmapScaleEnd(h),span=scaleEnd-h.start;if(!span)return 0;return Math.max(0,Math.min(100,(d-h.start)/span*100))}
function allocationActiveMonthsForDemand(d){return[...new Set(db.allocations.filter(a=>a.demandId===d.id&&a.teamMemberId).flatMap(a=>Object.entries(a.forecast||{}).filter(([,v])=>Number(v)>0).map(([m])=>normalizeMonthStart(m))).filter(Boolean))].sort()}
function demandResourceWindow(d){const activeMonths=allocationActiveMonthsForDemand(d);if(!activeMonths.length)return null;const first=activeMonths[0],[fy,fm]=first.split('-').map(Number),last=activeMonths[activeMonths.length-1],[ly,lm]=last.split('-').map(Number);return{start:new Date(fy,fm-1,1),end:new Date(ly,lm,1)}}
function ensureRoadmapStyles(){if(document.getElementById('roadmap-v12-styles'))return;const s=document.createElement('style');s.id='roadmap-v12-styles';s.textContent=`
.roadmap-legend{display:flex;gap:18px;flex-wrap:wrap;align-items:center;margin:0 0 14px;font-size:.82rem;color:var(--muted)}
.roadmap-legend span{display:inline-flex;align-items:center;gap:7px}.legend-plan{width:34px;height:2px;background:#344054;position:relative}.legend-plan:before{content:'';position:absolute;left:-3px;top:-3px;width:8px;height:8px;border-radius:50%;background:#344054}.legend-plan:after{content:'';position:absolute;right:-4px;top:-4px;width:8px;height:8px;background:#344054;transform:rotate(45deg)}.legend-resource{width:34px;height:8px;border-radius:999px;background:#345bd7}
.roadmap-track{height:44px;position:relative;touch-action:none}.roadmap-plan-line{position:absolute;top:12px;height:2px;background:#344054}.roadmap-resource-line{position:absolute;top:25px;height:9px;border-radius:999px;background:linear-gradient(90deg,#345bd7,#6d87ed);opacity:.9}.roadmap-marker{position:absolute;top:7px;width:12px;height:12px;background:#344054;transform:translateX(-50%);z-index:3}.roadmap-marker.start{border-radius:50%}.roadmap-marker.end{transform:translateX(-50%) rotate(45deg)}.roadmap-editing .roadmap-marker{cursor:ew-resize;box-shadow:0 0 0 4px rgba(52,64,84,.12)}.roadmap-marker:hover{box-shadow:0 0 0 5px rgba(52,64,84,.14)}.roadmap-date-caption{font-size:.72rem;color:var(--muted);margin-top:2px}.roadmap-row-editing{background:#fbfcff}.roadmap .road-row{min-height:54px}
`;document.head.appendChild(s)}
function renderRoadmapToolbar(){const el=$('roadmapToolbar');if(!el)return;el.innerHTML=roadmapState.editing?'<button class="btn success" id="saveRoadmap">Save Changes</button><button class="btn" id="cancelRoadmap">Cancel</button>':`<button class="btn primary" id="editRoadmap" ${workspaceHandle?'':'disabled'}>Edit Roadmap</button>`;$('editRoadmap')?.addEventListener('click',()=>{roadmapState.editing=true;roadmapState.draft=clone(db.demand);renderRoadmap()});$('cancelRoadmap')?.addEventListener('click',()=>{roadmapState.editing=false;roadmapState.draft=null;roadmapState.drag=null;renderRoadmap()});$('saveRoadmap')?.addEventListener('click',saveRoadmapChanges)}
function saveRoadmapChanges(){for(const next of roadmapState.draft){const old=demandById(next.id);if(!old)continue;const ns=next.workPackage?.targetStart||'',ne=next.workPackage?.targetEnd||'';if(ns&&ne&&ns>ne){alert(`${next.id}: start date cannot be after end date.`);return}if(old.workPackage?.targetStart!==ns||old.workPackage?.targetEnd!==ne){old.workPackage=old.workPackage||{};old.workPackage.targetStart=ns;old.workPackage.targetEnd=ne;old.version=(Number(old.version)||0)+1;old.modifiedAt=new Date().toISOString();markDirty('demand',old.id,`Updated roadmap dates for ${old.id}.`)}}roadmapState.editing=false;roadmapState.draft=null;roadmapState.drag=null;refreshAll()}
function renderRoadmap(){ensureRoadmapStyles();renderRoadmapToolbar();const h=roadmapHorizon(),head=$('timelineHead'),rowsEl=$('roadmapRows');if(!h){head.innerHTML='<span>Demand</span>';rowsEl.innerHTML='<span class="muted">No planning window configured.</span>';return}const {start,months}=h,scaleEnd=roadmapScaleEnd(h),step=100/months.length;head.style.gridTemplateColumns=`220px repeat(${months.length},1fr)`;head.innerHTML='<span>Demand</span>'+months.map(m=>`<span>${monthLabel(m)}</span>`).join('');const legend=$('roadmapLegend');if(legend)legend.innerHTML='<span><i class="legend-plan"></i>Planned demand window</span><span><i class="legend-resource"></i>Resourced period</span>';
rowsEl.innerHTML=roadmapDemandRows().filter(isOpenDemand).map(d=>{const ps=d.workPackage?.targetStart||'',pe=d.workPackage?.targetEnd||'',sp=datePct(ps,h),ep=datePct(pe,h),left=sp??0,right=ep??left,planWidth=Math.max(.2,right-left),rw=demandResourceWindow(d),rStart=rw?Math.max(0,Math.min(100,(rw.start-start)/(scaleEnd-start)*100)):null,rEnd=rw?Math.max(0,Math.min(100,(rw.end-start)/(scaleEnd-start)*100)):null,rWidth=rw?Math.max(1,rEnd-rStart):0;return`<div class="road-row ${roadmapState.editing?'roadmap-row-editing':''}" data-roadmap-row="${d.id}"><div><strong>${escHtml(d.title)}</strong><br><span class="muted">${escHtml(ownerName(d))}</span><div class="roadmap-date-caption" data-roadmap-caption="${d.id}">${ps||'No start'} → ${pe||'No end'}</div></div><div class="timeline roadmap-track ${roadmapState.editing?'roadmap-editing':''}" data-roadmap-track="${d.id}" style="background:repeating-linear-gradient(to right,transparent 0,transparent calc(${step}% - 1px),#e8edf5 calc(${step}% - 1px),#e8edf5 ${step}%)">${ps&&pe?`<div class="roadmap-plan-line" data-roadmap-plan="${d.id}" style="left:${left}%;width:${planWidth}%"></div><div class="roadmap-marker start" data-roadmap-handle="start" data-demand-id="${d.id}" style="left:${left}%" title="Planned start: ${ps}"></div><div class="roadmap-marker end" data-roadmap-handle="end" data-demand-id="${d.id}" style="left:${right}%" title="Planned end: ${pe}"></div>`:''}${rw?`<div class="roadmap-resource-line" style="left:${rStart}%;width:${rWidth}%" title="Resourced ${activeResourceLabel(d)}"></div>`:''}</div></div>`}).join('');if(roadmapState.editing)bindRoadmapDrag(h)}
function activeResourceLabel(d){const ms=allocationActiveMonthsForDemand(d);return ms.length?`${monthLabel(ms[0])} to ${monthLabel(ms[ms.length-1])}`:'not resourced'}
function updateRoadmapDragVisual(id,h){const rec=roadmapState.draft.find(x=>x.id===id);if(!rec)return;const startPct=datePct(rec.workPackage?.targetStart,h)??0,endPct=datePct(rec.workPackage?.targetEnd,h)??startPct,track=document.querySelector(`[data-roadmap-track="${id}"]`),start=track?.querySelector('[data-roadmap-handle="start"]'),end=track?.querySelector('[data-roadmap-handle="end"]'),line=track?.querySelector(`[data-roadmap-plan="${id}"]`),caption=document.querySelector(`[data-roadmap-caption="${id}"]`);if(start)start.style.left=`${startPct}%`;if(end)end.style.left=`${endPct}%`;if(line){line.style.left=`${startPct}%`;line.style.width=`${Math.max(.2,endPct-startPct)}%`}if(caption)caption.textContent=`${rec.workPackage?.targetStart||'No start'} → ${rec.workPackage?.targetEnd||'No end'}`}
function bindRoadmapDrag(h){const scaleEnd=roadmapScaleEnd(h);document.querySelectorAll('[data-roadmap-handle]').forEach(handle=>handle.addEventListener('pointerdown',e=>{e.preventDefault();const track=handle.closest('[data-roadmap-track]');roadmapState.drag={id:handle.dataset.demandId,kind:handle.dataset.roadmapHandle,track,pointerId:e.pointerId};handle.setPointerCapture?.(e.pointerId)}));document.querySelectorAll('[data-roadmap-track]').forEach(track=>{track.addEventListener('pointermove',e=>{const drag=roadmapState.drag;if(!drag||drag.track!==track)return;const rect=track.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)),d=new Date(h.start.getTime()+ratio*(scaleEnd-h.start)),date=isoDay(d),rec=roadmapState.draft.find(x=>x.id===drag.id);if(!rec)return;rec.workPackage=rec.workPackage||{};if(drag.kind==='start'){const finish=rec.workPackage.targetEnd;rec.workPackage.targetStart=finish&&date>finish?finish:date}else{const begin=rec.workPackage.targetStart;rec.workPackage.targetEnd=begin&&date<begin?begin:date}updateRoadmapDragVisual(drag.id,h)});const finishDrag=()=>{if(roadmapState.drag?.track===track){roadmapState.drag=null;renderRoadmap()}};track.addEventListener('pointerup',finishDrag);track.addEventListener('pointercancel',finishDrag)})}
const roadmapOriginalRefresh=refreshAll;refreshAll=function(){roadmapOriginalRefresh();renderRoadmap()};
ensureRoadmapStyles();renderRoadmap();
