const BACKUP_ROOT='backups';
const AUTOSAVE_DELAY_MS=500;
const AUTOSAVE_SAFETY_INTERVAL_MS=60000;
let autosaveTimer=null,autosaveRunning=false,autosaveQueued=false,workspaceChangeSerial=0;
function pad2(n){return String(n).padStart(2,'0')}
function pad3(n){return String(n).padStart(3,'0')}
function localBackupTimestamp(d=new Date()){return `${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}T${pad2(d.getHours())}-${pad2(d.getMinutes())}-${pad2(d.getSeconds())}-${pad3(d.getMilliseconds())}`}
function parseBackupTimestamp(name){const m=/^(\d{4})-(\d{2})-(\d{2})T(\d{2})-(\d{2})-(\d{2})(?:-(\d{3}))?$/.exec(name);if(!m)return null;const [,y,mo,d,h,mi,s,ms='0']=m,date=new Date(Number(y),Number(mo)-1,Number(d),Number(h),Number(mi),Number(s),Number(ms));return Number.isNaN(date.getTime())?null:date}
function dayKey(d){return `${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}`}
function monthKey(d){return `${d.getFullYear()}-${pad2(d.getMonth()+1)}`}
function startOfDay(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
async function copyFile(sourceHandle,destDir,name){const file=await sourceHandle.getFile(),dest=await destDir.getFileHandle(name,{create:true}),w=await dest.createWritable();await w.write(await file.arrayBuffer());await w.close()}
async function copyJsonDirectory(sourceRoot,destRoot,folderName){let src;try{src=await sourceRoot.getDirectoryHandle(folderName)}catch(e){if(e.name==='NotFoundError')return;throw e}const dest=await destRoot.getDirectoryHandle(folderName,{create:true});for await(const [name,handle] of src.entries()){if(handle.kind==='file'&&name.toLowerCase().endsWith('.json'))await copyFile(handle,dest,name)}}
async function createWorkspaceBackup(rootHandle){const backups=await rootHandle.getDirectoryHandle(BACKUP_ROOT,{create:true}),name=localBackupTimestamp(),snapshot=await backups.getDirectoryHandle(name,{create:true});const workspaceFile=await rootHandle.getFileHandle('workspace.json');await copyFile(workspaceFile,snapshot,'workspace.json');for(const folder of ['demand','team','allocations','config'])await copyJsonDirectory(rootHandle,snapshot,folder);await writeJson(snapshot,'backup-manifest.json',{type:'architecture-operations-hub-backup',createdAt:new Date().toISOString(),sourceWorkspace:rootHandle.name,retention:'all today; first per day within 7 days; first per month thereafter'});log(`Created workspace backup ${BACKUP_ROOT}/${name}.`);return name}
async function pruneWorkspaceBackups(rootHandle,now=new Date()){let backups;try{backups=await rootHandle.getDirectoryHandle(BACKUP_ROOT)}catch(e){if(e.name==='NotFoundError')return;throw e}const entries=[];for await(const [name,handle] of backups.entries()){if(handle.kind!=='directory')continue;const parsed=parseBackupTimestamp(name);if(parsed)entries.push({name,date:parsed})}entries.sort((a,b)=>a.date-b.date);const today=startOfDay(now),weekStart=new Date(today);weekStart.setDate(weekStart.getDate()-6);const keep=new Set(),daily=new Map(),monthly=new Map();for(const entry of entries){const d=startOfDay(entry.date);if(d.getTime()===today.getTime()){keep.add(entry.name);continue}if(d>=weekStart&&d<today){const key=dayKey(entry.date);if(!daily.has(key)){daily.set(key,entry.name);keep.add(entry.name)}continue}const key=monthKey(entry.date);if(!monthly.has(key)){monthly.set(key,entry.name);keep.add(entry.name)}}let removed=0;for(const entry of entries){if(keep.has(entry.name))continue;await backups.removeEntry(entry.name,{recursive:true});removed++}if(removed)log(`Backup retention removed ${removed} superseded backup${removed===1?'':'s'}.`)}
async function backupWorkspaceOnOpen(rootHandle){if(!await ensureRW(rootHandle))throw new Error('Read/write permission is required to create the workspace safety backup.');await createWorkspaceBackup(rootHandle);await pruneWorkspaceBackups(rootHandle)}
function requestAutosave(delay=AUTOSAVE_DELAY_MS){if(!workspaceHandle||!dirtyCount())return;workspaceChangeSerial++;clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>flushAutosave(),delay)}
async function flushAutosave(){if(!workspaceHandle||!dirtyCount())return;if(autosaveRunning){autosaveQueued=true;return}autosaveRunning=true;try{await saveWorkspace({silent:true,reason:'Autosave'})}finally{autosaveRunning=false;if(autosaveQueued||dirtyCount()){autosaveQueued=false;clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>flushAutosave(),250)}}}
setInterval(()=>{if(workspaceHandle&&dirtyCount())flushAutosave()},AUTOSAVE_SAFETY_INTERVAL_MS);
