/* Roadmap is a read-only comparison of Work Package delivery windows and Demand-level resource allocation.
   Delivery dates are authored on Work Packages, not on Defined Demand. */
const roadmapState={editing:false,draft:null,drag:null};
function roadmapHorizon(){const months=planningPeriods();if(!months.length)return null;const first=months[0],[fy,fm]=first.split('-').map(Number),last=months[months.length-1],[ly,lm]=last.split('-').map(Number);return{start:new Date(fy,fm-1,1),end:new Date(ly,lm,1),months}}
function roadmapScaleEnd(h){const [y,m]=h.months[h.months.length-1].split('-').map(Number);return new Date(y,m,1)}
function datePct(value,h){if(!value)return null;const d=new Date(`${value}T00:00:00`),scaleEnd=roadmapScaleEnd(h),span=scaleEnd-h.start;if(!span)return 0;return Math.max(0,Math.min(100,(d-h.start)/span*100))}
function allocationActiveMonthsForDemand(d){return[...new Set(db.allocations.filter(a=>a.demandId===d.id&&a.teamMemberId).flatMap(a=>Object.entries(a.forecast||{}).filter(([,v])=>Number(v)>0).map(([m])=>normalizeMonthStart(m))).filter(Boolean))].sort()}
function demandResourceWindow(d){const activeMonths=allocationActiveMonthsForDemand(d);if(!activeMonths.length)return null;const first=activeMonths[0],[fy,fm]=first.split('-').map(Number),last=activeMonths[activeMonths.length-1],[ly,lm]=last.split('-').map(Number);return{start:new Date(fy,fm-1,1),end:new Date(ly,lm,1)}}
function demandDeliveryWindow(d){const summary=window.WorkPackages?.summaryForDemand?.(d.id);if(summary&&(summary.start||summary.end))return{start:summary.start,end:summary.end,source:'Work Packages'};const legacy=window.DefinedDemandModel?.legacyDeliveryWindow?.(d);if(legacy?.legacy)return{start:legacy.start,end:legacy.end,source:'Legacy Demand dates'};return{start:'',end:'',source:'Not planned'}}
function ensureRoadmapStyles(){if(document.getElementById('roadmap-v13-styles'))return;const s=document.createElement('style');s.id='roadmap-v13-styles';s.textContent=`
.roadmap-legend{display:flex;gap:18px;flex-wrap:wrap;align-items:center;margin:0 0 14px;font-size:.82rem;color:var(--muted)}.roadmap-legend span{display:inline-flex;align-items:center;gap:7px}.legend-plan{width:34px;height:2px;background:#344054;position:relative}.legend-plan:before{content:'';position:absolute;left:-3px;top:-3px;width:8px;height:8px;border-radius:50%;background:#344054}.legend-plan:after{content:'';position:absolute;right:-4px;top:-4px;width:8px;height:8px;background:#344054;transform:rotate(45deg)}.legend-resource{width:34px;height:8px;border-radius:999px;background:#345bd7}.roadmap-track{height:44px;position:relative}.roadmap-plan-line{position:absolute;top:12px;height:2px;background:#344054}.roadmap-resource-line{position:absolute;top:25px;height:9px;border-radius:999px;background:linear-gradient(90deg,#345bd7,#6d87ed);opacity:.9}.roadmap-marker{position:absolute;top:7px;width:12px;height:12px;background:#344054;transform:translateX(-50%);z-index:3}.roadmap-marker.start{border-radius:50%}.roadmap-marker.end{transform:translateX(-50%) rotate(45deg)}.roadmap-date-caption{font-size:.72rem;color:var(--muted);margin-top:2px}.roadmap-source{font-size:.68rem;color:var(--muted);margin-top:1px}.roadmap .road-row{min-height:54px}`;document.head.appendChild(s)}
function renderRoadmapToolbar(){const el=$('roadmapToolbar');if(el)el.innerHTML='<span class="muted">Edit delivery dates on the child Work Packages in the Demand record.</span>'}
function activeResourceLabel(d){const ms=allocationActiveMonthsForDemand(d);return ms.length?`${monthLabel(ms[0])} to ${monthLabel(ms[ms.length-1])}`:'not resourced'}
function renderRoadmap(){ensureRoadmapStyles();renderRoadmapToolbar();const h=roadmapHorizon(),head=$('timelineHead'),rowsEl=$('roadmapRows');if(!h){head.innerHTML='<span>Demand</span>';rowsEl.innerHTML='<span class="muted">No planning window configured.</span>';return}const {start,months}=h,scaleEnd=roadmapScaleEnd(h),step=100/months.length;head.style.gridTemplateColumns=`220px repeat(${months.length},1fr)`;head.innerHTML='<span>Demand</span>'+months.map(m=>`<span>${monthLabel(m)}</span>`).join('');const legend=$('roadmapLegend');if(legend)legend.innerHTML='<span><i class="legend-plan"></i>Work Package delivery window</span><span><i class="legend-resource"></i>Demand resourced period</span>';
rowsEl.innerHTML=db.demand.filter(isOpenDemand).map(d=>{const dw=demandDeliveryWindow(d),ps=dw.start||'',pe=dw.end||'',sp=datePct(ps,h),ep=datePct(pe,h),left=sp??0,right=ep??left,planWidth=Math.max(.2,right-left),rw=demandResourceWindow(d),rStart=rw?Math.max(0,Math.min(100,(rw.start-start)/(scaleEnd-start)*100)):null,rEnd=rw?Math.max(0,Math.min(100,(rw.end-start)/(scaleEnd-start)*100)):null,rWidth=rw?Math.max(1,rEnd-rStart):0;return`<div class="road-row" data-roadmap-row="${escHtml(d.id)}"><div><strong>${escHtml(d.title)}</strong><br><span class="muted">${escHtml(ownerName(d))}</span><div class="roadmap-date-caption">${ps||'No start'} → ${pe||'No end'}</div><div class="roadmap-source">${escHtml(dw.source)}</div></div><div class="timeline roadmap-track" style="background:repeating-linear-gradient(to right,transparent 0,transparent calc(${step}% - 1px),#e8edf5 calc(${step}% - 1px),#e8edf5 ${step}%)">${ps&&pe?`<div class="roadmap-plan-line" style="left:${left}%;width:${planWidth}%"></div><div class="roadmap-marker start" style="left:${left}%" title="Earliest Work Package start: ${escHtml(ps)}"></div><div class="roadmap-marker end" style="left:${right}%" title="Latest Work Package end: ${escHtml(pe)}"></div>`:''}${rw?`<div class="roadmap-resource-line" style="left:${rStart}%;width:${rWidth}%" title="Resourced ${escHtml(activeResourceLabel(d))}"></div>`:''}</div></div>`}).join('')}
const roadmapOriginalRefresh=refreshAll;refreshAll=function(){roadmapOriginalRefresh();renderRoadmap()};
window.addEventListener('amo:work-packages-updated',()=>renderRoadmap());
ensureRoadmapStyles();renderRoadmap();
