const ideaState={editing:false,draft:null,deleted:new Set(),filters:{id:'',raisedBy:'',raisedDate:'',title:'',description:'',status:''},sort:'raisedDate',direction:'desc'};
const ideaCols=[
  {key:'id',label:'Idea ID',type:'text',editable:false},
  {key:'raisedBy',label:'Raised By',type:'text',editable:true},
  {key:'raisedDate',label:'Raised Date',type:'date',editable:true},
  {key:'title',label:'Title',type:'text',editable:true},
  {key:'description',label:'Description',type:'text',editable:true},
  {key:'status',label:'Status',type:'select',editable:true,values:()=>db.settings.ideaStatuses||DEFAULT_SETTINGS.ideaStatuses}
];
function ideaRows(){const source=ideaState.editing?ideaState.draft:db.ideas;let rows=source.filter(r=>!ideaState.deleted.has(r.id)&&ideaCols.every(c=>{const f=String(ideaState.filters[c.key]||'').toLowerCase();return!f||String(r[c.key]??'').toLowerCase().includes(f)}));if(ideaState.sort){const k=ideaState.sort;rows=[...rows].sort((a,b)=>String(a[k]??'').localeCompare(String(b[k]??''),undefined,{numeric:true,sensitivity:'base'}));if(ideaState.direction==='desc')rows.reverse()}return rows}
function ideaSortMark(key){return ideaState.sort===key?(ideaState.direction==='asc'?' ↑':' ↓'):' ↕'}
function toggleIdeaSort(key){if(ideaState.sort!==key){ideaState.sort=key;ideaState.direction='asc'}else if(ideaState.direction==='asc')ideaState.direction='desc';else if(ideaState.direction==='desc'){ideaState.sort=null;ideaState.direction=null}else{ideaState.sort=key;ideaState.direction='asc'}renderIdeas()}
function ideaFilterControl(c){const v=ideaState.filters[c.key]||'',fk=`idea:${c.key}`;if(c.type==='select')return`<select data-idea-filter="${c.key}" data-filter-key="${fk}"><option value="">All</option>${(c.values?.()||[]).map(x=>`<option ${x===v?'selected':''}>${escHtml(x)}</option>`).join('')}</select>`;return`<input data-idea-filter="${c.key}" data-filter-key="${fk}" value="${escHtml(v)}" placeholder="contains…">`}
function ideaEditControl(r,c){const v=r[c.key]??'';if(!c.editable)return`<span class="nowrap">${escHtml(v)}</span>`;if(c.type==='select')return`<select class="cell-input" data-idea-field="${c.key}" data-idea-id="${r.id}">${(c.values?.()||[]).map(x=>`<option ${x===v?'selected':''}>${escHtml(x)}</option>`).join('')}</select>`;return`<input class="cell-input" type="${c.type==='date'?'date':'text'}" data-idea-field="${c.key}" data-idea-id="${r.id}" value="${escHtml(v)}">`}
function renderIdeas(){const toolbar=$('ideaToolbar'),table=$('ideaTable'),count=$('ideaCount');if(!toolbar||!table)return;const rows=ideaRows();toolbar.innerHTML=ideaState.editing?'<button class="btn primary" id="newIdeaBtn">New Idea</button><button class="btn success" id="saveIdeasBtn">Save Changes</button><button class="btn" id="cancelIdeasBtn">Cancel</button><button class="btn" id="clearIdeaFiltersBtn">Clear Filters</button>':`<button class="btn primary" id="newIdeaBtn" ${workspaceHandle?'':'disabled'}>New Idea</button><button class="btn" id="editIdeasBtn" ${workspaceHandle?'':'disabled'}>Edit List</button><button class="btn" id="clearIdeaFiltersBtn">Clear Filters</button>`;count.textContent=workspaceHandle?`Showing ${rows.length} of ${(ideaState.editing?ideaState.draft:db.ideas).length-ideaState.deleted.size} ideas`:'No workspace loaded';table.innerHTML=`<thead><tr>${ideaCols.map(c=>`<th><button class="sort-btn" data-idea-sort="${c.key}">${c.label}${ideaSortMark(c.key)}</button></th>`).join('')}${ideaState.editing?'<th>Delete</th>':''}</tr><tr class="filter-row">${ideaCols.map(c=>`<th>${ideaFilterControl(c)}</th>`).join('')}${ideaState.editing?'<th></th>':''}</tr></thead><tbody>${rows.map(r=>`<tr data-idea-row="${r.id}" class="${dirtyRecords.ideas.has(r.id)?'row-dirty':''}">${ideaCols.map(c=>`<td>${ideaState.editing?ideaEditControl(r,c):escHtml(r[c.key]??'')}</td>`).join('')}${ideaState.editing?`<td><button class="btn danger" data-idea-delete="${r.id}">Delete</button></td>`:''}</tr>`).join('')}</tbody>`;
  table.querySelectorAll('[data-idea-sort]').forEach(b=>b.onclick=()=>toggleIdeaSort(b.dataset.ideaSort));
  table.querySelectorAll('[data-idea-filter]').forEach(el=>el.addEventListener('input',e=>{const key=e.target.dataset.ideaFilter,pos=e.target.selectionStart;clearTimeout(debounceTimers[`idea-${key}`]);ideaState.filters[key]=e.target.value;debounceTimers[`idea-${key}`]=setTimeout(()=>{renderIdeas();requestAnimationFrame(()=>{const n=document.querySelector(`[data-filter-key="idea:${key}"]`);n?.focus({preventScroll:true});n?.setSelectionRange?.(pos,pos)})},350)}));
  table.querySelectorAll('tbody tr[data-idea-row]').forEach(tr=>tr.ondblclick=e=>{if(e.target.closest('button,input,select,textarea'))return;openIdeaModal(tr.dataset.ideaRow,'view')});
  $('newIdeaBtn')?.addEventListener('click',()=>openIdeaModal(null,'edit'));
  $('editIdeasBtn')?.addEventListener('click',()=>{ideaState.editing=true;ideaState.draft=clone(db.ideas);ideaState.deleted=new Set();renderIdeas()});
  $('cancelIdeasBtn')?.addEventListener('click',()=>{ideaState.editing=false;ideaState.draft=null;ideaState.deleted=new Set();renderIdeas()});
  $('clearIdeaFiltersBtn')?.addEventListener('click',()=>{ideaState.filters={id:'',raisedBy:'',raisedDate:'',title:'',description:'',status:''};renderIdeas()});
  if(ideaState.editing){table.querySelectorAll('[data-idea-field]').forEach(el=>el.onchange=e=>{const r=ideaState.draft.find(x=>x.id===e.target.dataset.ideaId);if(r)r[e.target.dataset.ideaField]=e.target.value});table.querySelectorAll('[data-idea-delete]').forEach(b=>b.onclick=()=>{ideaState.deleted.add(b.dataset.ideaDelete);renderIdeas()});$('saveIdeasBtn').onclick=saveIdeas}
}
function nextIdeaId(){const rows=ideaState.editing?ideaState.draft:db.ideas,max=Math.max(0,...rows.map(x=>Number((x.id||'').match(/(\d+)$/)?.[1]||0)));return`IDEA-${CURRENT_YEAR}-${String(max+1).padStart(4,'0')}`}
function defaultIdea(){return{id:nextIdeaId(),raisedBy:'',raisedDate:new Date().toISOString().slice(0,10),title:'',description:'',status:(db.settings.ideaStatuses||DEFAULT_SETTINGS.ideaStatuses)[0]||'New',version:1}}
const ideaModalState={id:null,mode:'view',isNew:false,draft:null};
function ideaSource(){return ideaState.editing?ideaState.draft:db.ideas}
function openIdeaModal(id=null,mode=null){if(!workspaceHandle)return;ideaModalState.id=id;ideaModalState.isNew=!id;ideaModalState.mode=mode||(id?'view':'edit');ideaModalState.draft=id?null:defaultIdea();$('recordModalBackdrop').classList.add('open');renderIdeaModal()}
function closeIdeaModal(){$('recordModalBackdrop').classList.remove('open');Object.assign(ideaModalState,{id:null,mode:'view',isNew:false,draft:null})}
function ideaModalRecord(){if(ideaModalState.mode==='edit'&&ideaModalState.draft)return ideaModalState.draft;if(ideaModalState.isNew)return ideaModalState.draft;return ideaSource().find(x=>x.id===ideaModalState.id)}
function ideaField(label,key,value,type='text',opts=null,required=false,full=false,readonly=false){const cls=`field${full?' full':''}`,req=required?' *':'';if(ideaModalState.mode==='view')return`<div class="${cls}"><label>${label}${req}</label><div class="record-value ${value==null||value===''?'empty':''}">${value==null||value===''?'—':escHtml(value)}</div></div>`;if(type==='select')return`<div class="${cls}"><label>${label}${req}</label><select data-idea-modal-field="${key}" ${readonly?'disabled':''}>${(opts||[]).map(x=>`<option ${String(x)===String(value)?'selected':''}>${escHtml(x)}</option>`).join('')}</select></div>`;if(type==='textarea')return`<div class="${cls}"><label>${label}${req}</label><textarea data-idea-modal-field="${key}" ${readonly?'disabled':''}>${escHtml(value)}</textarea></div>`;return`<div class="${cls}"><label>${label}${req}</label><input data-idea-modal-field="${key}" type="${type}" value="${escHtml(value??'')}" ${readonly?'disabled':''}></div>`}
function renderIdeaModal(){const r=ideaModalRecord();if(!r)return;$('recordModalTitle').textContent=ideaModalState.isNew?'New Idea':`Idea ${r.id}`;$('recordModalSubtitle').textContent=ideaModalState.isNew?'Create a new improvement idea':ideaModalState.mode==='view'?'View idea':'Edit idea';$('recordModalBody').innerHTML=`<div class="record-form">${ideaField('Idea ID','id',r.id,'text',null,false,false,true)}${ideaField('Raised By','raisedBy',r.raisedBy,'text',null,true)}${ideaField('Raised Date','raisedDate',r.raisedDate,'date',null,true)}${ideaField('Title','title',r.title,'text',null,true)}${ideaField('Status','status',r.status,'select',db.settings.ideaStatuses||DEFAULT_SETTINGS.ideaStatuses,true)}${ideaField('Description','description',r.description,'textarea',null,true,true)}</div>`;$('recordModalActions').innerHTML=ideaModalState.mode==='view'?'<button class="btn" id="closeIdeaModal">Close</button><button class="btn primary" id="editIdeaModal">Edit</button>':'<button class="btn" id="cancelIdeaModal">Cancel</button><button class="btn success" id="saveIdeaModal">Save</button>';$('closeIdeaModal')?.addEventListener('click',closeIdeaModal);$('editIdeaModal')?.addEventListener('click',()=>{ideaModalState.mode='edit';ideaModalState.draft=clone(r);renderIdeaModal()});$('cancelIdeaModal')?.addEventListener('click',()=>{if(ideaModalState.isNew)closeIdeaModal();else{ideaModalState.mode='view';ideaModalState.draft=null;renderIdeaModal()}});$('saveIdeaModal')?.addEventListener('click',saveIdeaModal)}
function readIdeaModal(){const r=clone(ideaModalState.draft||ideaModalRecord());$('recordModalBody').querySelectorAll('[data-idea-modal-field]').forEach(el=>r[el.dataset.ideaModalField]=el.value);return r}
function saveIdeaModal(){const next=readIdeaModal();if(!next.raisedBy.trim()||!next.raisedDate||!next.title.trim()||!next.description.trim()||!next.status){alert('Raised By, Raised Date, Title, Description and Status are required.');return}if(ideaModalState.isNew){if(ideaState.editing)ideaState.draft.push(next);else{db.ideas.push(next);markDirty('ideas',next.id,`Created ${next.id}.`)}}else if(ideaState.editing){Object.assign(ideaState.draft.find(x=>x.id===ideaModalState.id),next)}else{const old=db.ideas.find(x=>x.id===ideaModalState.id);Object.assign(old,next);old.version=(Number(old.version)||0)+1;old.modifiedAt=new Date().toISOString();markDirty('ideas',old.id,`Updated ${old.id}.`)}closeIdeaModal();renderIdeas();updateBanner()}
function saveIdeas(){const invalid=ideaState.draft.filter(x=>!ideaState.deleted.has(x.id)&&(!String(x.raisedBy||'').trim()||!x.raisedDate||!String(x.title||'').trim()||!String(x.description||'').trim()||!x.status));if(invalid.length){alert('All Idea fields are required. Missing values: '+invalid.map(x=>x.id).join(', '));return}const original=db.ideas;for(const next of ideaState.draft){if(ideaState.deleted.has(next.id))continue;const old=original.find(x=>x.id===next.id);if(!old){original.push(clone(next));markDirty('ideas',next.id,`Created ${next.id}.`)}else if(JSON.stringify(old)!==JSON.stringify(next)){Object.assign(old,clone(next));old.version=(Number(old.version)||0)+1;old.modifiedAt=new Date().toISOString();markDirty('ideas',old.id,`Updated ${old.id}.`)}}for(const id of ideaState.deleted){deletedIdeas.add(id);dirtyRecords.ideas.delete(id)}db.ideas=db.ideas.filter(x=>!ideaState.deleted.has(x.id));ideaState.editing=false;ideaState.draft=null;ideaState.deleted=new Set();updateBanner();renderIdeas();if(typeof requestAutosave==='function')requestAutosave()}
const _refreshAll=refreshAll;refreshAll=function(){_refreshAll();renderIdeas()};
const _switchView=switchView;switchView=function(id){_switchView(id);if(id==='ideas')$('pageTitle').textContent='Ideas'};
renderIdeas();
